### ISSUE TITLE
case 'doneRecording': throws in recorderWorker.js

### ISSUE THREAD

**Issue by lafferty** [chris-rudmin/Recorderjs#1]
Nice piece of work!

I did noticed the case 'doneRecoding' in recorderWorker.js throw when e.data.recordOpus is false.  Seems instanceof fail, because importScripts( 'oggopus.js' ) has not run and the type has not loaded.The behaviour is a bit annoying in a Chrome's debugger, because it halts the worker thread.  Here's the snippet:

```
case 'doneRecording':
      if ( this.recorder instanceof OggOpus ) {
        this.recorder.encodeFinalFrame();
      }
      break;

case 'init':
      if ( e.data.recordOpus ) {
        importScripts( 'oggopus.js' );
        this.recorder = new OggOpus( e.data );
      }
      else {
        importScripts( 'wavepcm.js' );
        this.recorder = new WavePCM( e.data );
      }
      break;
```

**Comment by chris-rudmin** [comment]
Good catch. Fixed in 6f4fed6.
