### ISSUE TITLE
not issue but question (could not figure out where else to put this)

### ISSUE THREAD

**Issue by edwardsmarkf** [chris-rudmin/Recorderjs#10]
hi - i have recently hired a programmer to combine the opus-recorder.js with 

https://github.com/binaryjs/binaryjs

so the uploading would happen while the recorder is running.  i am unfamiliar with forks, especially combining two existing githubs.   any suggestions or advice?  i am considering making the combination of the two open-sourced and any advice would be very much appreciated.

mark at edwardsmark(dot)com.

**Comment by chris-rudmin** [comment]
I don't know if you are aware, but the Ogg container is designed to be streamed (it provides data chunks as pages). If you enable the streaming option, RecorderJS will publish the pages as they are ready. 

I don't see the integration of these two components being problematic, so there might not be too much value in spending effort to make the combination a new open sourced project. That's up to you I guess.

Good luck and keep me posted on your results.

**Comment by edwardsmarkf** [comment]
hello chris - thank you for writing me back.  here is the project thus far:
 http://130.255.188.231:22810/   you are probably correct in the component
integration.  but i would be happy to share any and all of with you if you
think its of any value.  i don't possess the time, skill or patience to try
this myself which is why i hired somebody to do this for me.


Thank you,

Mark Edwards
