### ISSUE TITLE
Use wav encoder, set encoderSampleRate 16k but the result is 44.1k.

### ISSUE THREAD

**Issue by zawdd** [chris-rudmin/Recorderjs#101]
I use wav encoder, and set the encoder sample rate with 16k, 1 channel and 16bits depth.but when I use MediaInfo to analysis the audio, it shows that the sample rate is 44.1k. is there any problem with wav encoder?

**Comment by chris-rudmin** [comment]
the only supported option for the wav recorder is wavbitdepth. Resampling is currently not supported. The recorded sample rate  will be that of your audio device. The read me could probably be a bit clearer about that.

**Comment by zawdd** [comment]
thank you, I use the ffmpeg to trans the audio from 44.1k to 16k. I use a speech api (like google speech api) which only 8k or 16k is received, so I think if you can update the Recorderjs, it will be more useful. anyway thank you!

**Comment by chris-rudmin** [comment]
The primary use for this library is ogg opus encoding in the browser. The
resampler works quite well if recording to ogg opus. You will get much
smaller file than wave and it works with google speech API.
