### ISSUE TITLE
WebAssembly Opus encoder

### ISSUE THREAD

**Issue by MRSalomao** [chris-rudmin/Recorderjs#102]
Just out of curiosity, have you tried compiling a WebAssembly version of the Opus encoder? Do you think it would provide a significant performance improvement over the current javascript version of the encoder?

**Comment by chris-rudmin** [comment]
I haven’t tried it, but it is certainly testable. Emscripten supports
outputting to web assembly.

**Comment by chris-rudmin** [comment]
@MRSalomao I will make a new branch to investigate and will keep you posted. :)

**Comment by MRSalomao** [comment]
Awesome, @chris-rudmin! Thanks!
So far I have no experience with Emscripten, and a limited knowledge about makefiles. But I would like to investigate it as well in the near future. ;)

**Comment by chris-rudmin** [comment]
@MRSalomao I made a few changes to get WebAssembly version working. Feel like doing some benchmarking? :) 

https://github.com/chris-rudmin/Recorderjs/tree/webassembly

**Comment by chris-rudmin** [comment]
Notes about performance in Chrome: 

File Size:
- WebAssembly (wasm + js) is 269Kb (229.5Kb gzip)
- asm.js monolith script is 472Kb (132Kb gzip).

Startup time:
- WebAssembly is ~3 seconds (does async fetching of wasm).
- asm.js monolith script is ~2.5 seconds.

Encoding Speed on iMac 3.2Ghz core i5
- WASM average encoding a single 4096 buffer with default settings ~1.2ms
- asm.js average encoding a single 4096 buffer with default settings ~1.5ms

**Comment by chris-rudmin** [comment]
Web assembly seems to have the performance advantage when executing code, however gzip file size is larger and startup time is longer.

**Comment by MRSalomao** [comment]
Hey @chris-rudmin! Thank you! That was very kind of you :)

I'm in a rush these days (moving apartments), but as soon as I can run some tests I will post my results here.

That's an interesting tradeoff. Since in the application I'm developing the user is not immediately presented with the OPUS encoding feature, I might be able to seamlessly load and start the script after the initial page load.

Best!

**Comment by chris-rudmin** [comment]
I merged to master, open any new issues if you encounter them!
