### ISSUE TITLE
support record audio chunk-by-chunk

### ISSUE THREAD

**Issue by truongdo** [chris-rudmin/Recorderjs#105]
Hi,

I'd like to use this library to record audio chunk-by-chunk and send it to a server.
I've tried to enable the `streamPages` option, but the `dataAvailable` wasn't fired for every chunk.

Does this library support get chunk of data? (For example, the `dataAvailable` event is fired for every
1024 bytes).

**Comment by chris-rudmin** [comment]
Ogg opus chunks it’s encoded audio into packets which are then collected
into pages. If streamPages is true each page is emitted in the data
available event. Unfortunately it is not possible to encode packets and
pages of a fixed size.  To send fixed size data to your server, simply
collect the data into a buffer and when it is filled, send it, flush the
buffer and repeat.

**Comment by truongdo** [comment]
Thanks for the reply! I've switched from `wavWorker.min.js` to `encoderWorker.min.js`.
The `dataAvailabled` is fired chunk-by-chunk now, but it is quite slow and the data length varies significantly between each `dataAvailabled` fired. This there any option I can make the data length
consistent or at least not so much different than below.

```
Data available with length 47
record_control.js:74 Data available with length 54
record_control.js:74 Data available with length 4144
record_control.js:74 Data available with length 4297
record_control.js:74 Data available with length 4255
record_control.js:74 Data available with length 4172
record_control.js:74 Data available with length 985
```

Here is my configuration:
```
        monitorGain: 0,
        numberOfChannels: 1,
        wavBitDepth: 16,
        encoderPath: "/static/js/encoderWorker.min.js",
        streamPages: true,
        encoderSampleRate: 16000,
        maxBuffersPerPage: 20,
        resampleQuality: 10
```

**Comment by chris-rudmin** [comment]
@truongdo All the options are documented in the readme.
