### ISSUE TITLE
Request: ability to decode back to buffers

### ISSUE THREAD

**Issue by paullewis** [chris-rudmin/Recorderjs#12]
I'm working on at a bit of code which stores generated audio files in IndexedDB, but also uses the Web Audio API as well.

As it stands your version of Recorderjs is _epic_ and works amazingly well, but because Chrome's implementation doesn't support Opus in `decodeAudioData`, when I pass an ogg file in it fails to decode. I can see from the emscriptened libopus that the decode functionality is there, but that Recorderjs doesn't have a corresponding `decode` call. Is there any chance you can add it? I'd do a PR, but I'm not quite sure how to work with the emscriptened code, I'm afraid :-/

**Comment by chris-rudmin** [comment]
I had the decode audio logic in the lib, but decided to remove it, because:
- Decoding and playback is outside the scope of a recording lib.
- Up to date browsers can usually play ogg audio with the audio tag.

You can reference the decoder code [here](https://github.com/chris-rudmin/Recorderjs/blob/2c1ab2ae61bf5ee4c224b461135215f2957f434e/oggopus.js#L19)

Alternatively, perhaps there is a way to get the PCM out of an audio tag?

**Comment by paullewis** [comment]
Makes perfect sense that you removed it :) In my case I can't use the `<audio>` element or `new Audio` because I require an `offlineAudioContext`, which is a bit of a bummer!

One question from me: the `decode` function takes packets. How does that map to the ogg file blob? Do I convert over to an `arraybuffer` and fire it into that, or do I need to break it up in some way? Sorry for the noob questions, and thank you again for all your hard work on this.

**Comment by chris-rudmin** [comment]
To get the packets out of an ogg file, you will need to parse each page, and then parse the segment table to get the packet boundaries. I've seen some libs around which can do this.  I think speex.js has something and perhaps aurora.js as well.

**Comment by chris-rudmin** [comment]
If you can follow the logic after encode(), you need to do the same, but backwards.

**Comment by chris-rudmin** [comment]
I have created a new branch for opus only operation. I have included a decoder for completeness. It has not been documented or thoroughly tested, but the happy path is working. [Check it out](https://github.com/chris-rudmin/Recorderjs/tree/opus-only) if you are still in need.

**Comment by chris-rudmin** [comment]
Merged decoder which allows decoding back to buffers.

**Comment by paullewis** [comment]
Oh boy, I'm _only just_ catching up on this. It's super that you broke them out to two separate scripts - thank you!

**Comment by jlev** [comment]
@chris-rudmin Any chance you could write a little documentation on how to use the decoding script? I'm trying to use your excellent library to record audio for Twilio, which only accepts [mp3, wav, aiff or ulaw](https://www.twilio.com/docs/api/twiml/play), but unfortunately not ogg/opus. So I can either store the files as ogg on the server and transcode with ffmpeg before sending to Twilio, or get access to the buffers after downsampling and save them as wav.

**Comment by chris-rudmin** [comment]
You create a worker with the decoder and then pass it a typed array with your encoded data along with the decode command. Sounds like it might be easier to use the original recorder is and record wav.
