### ISSUE TITLE
Request: detach/destroy or getUserMedia stream.end() ability

### ISSUE THREAD

**Issue by Kequc** [chris-rudmin/Recorderjs#13]
The first time an instance of Recorder is created, the user is asked for access to their microphone. In chrome this adds a red icon to the tab. There isn't any way seemingly to end the stream.

In my application I'm creating a new Recorder instance each time I want to record, is this an incorrect way to do things? I've added this.

    recorder.addEventListener 'stop', =>
      if recorder && recorder.stream
        recorder.stream.stop()

It would be nice if I could de-initialise the stream as an intended feature of the library.

**Comment by chris-rudmin** [comment]
The recorder object is intended to be reused and thus holds onto the stream
and the users permissions. The code you provided will stop the stream
properly, if you want the memory to be freed, you should also remove all
your event listeners as well. Javascript doesn't provide a nice way to
destroy objects so I left it out. When the recorder stops, the workers are
destroyed and the audio nodes disconnected from the destination so the
memory usage should minimal, and no extraneous events should be firing. Let
me know if this is in line with what you experience.

**Comment by chris-rudmin** [comment]
Forgot to say thanks for your comment, and I will consider adding a destroy() method if It could be implemented nicely.

**Comment by Kequc** [comment]
The reason I suppose I bring it up is that users might be confused and think their browser is still listening to them. Which it could. I love this library by the way, I was dealing with just raw pcm before I found this. Good work, everyone past and present who has worked on it.

**Comment by Kequc** [comment]
Here is my solution to do what I wanted. Taking into consideration that you said the Recorder is intended to be reused.

    _closeStream: =>
      # Close recorder stream

      if @recorder && @recorder.stream
        @recorder.stream.stop()
      @status.ready = false

    start: =>
      # Start recording
      return false if @status.active || @status.ready

      @status.active = true

      if @recorder
        @recorder.initStream()

      else
        @recorder = new Recorder
          recordOpus:
            stream: true

        @recorder.addEventListener 'streamReady', =>
          if @status.active
            @status.ready = true
            @recorder.start()
          else
            @_closeStream()

        @recorder.addEventListener 'stop', =>
          @_closeStream()

      @recorder

    stop: =>
      # Stop recording
      return false unless @status.active

      @status.active = false

      @recorder.stop()

The idea is that a stream is closed when the recorder is stopped and a new stream is initialised on start. This serves my needs. I hope it's not too messy looking.

**Comment by chris-rudmin** [comment]
Looks good.  I believe you can safely call start and stop and if recorder
is not in the right state nothing will happen. Recorder is also storing its
state in recorder.state (inactive, recording, or paused) if you want to
read from it as well.

**Comment by chris-rudmin** [comment]
Heads-up that i have experienced empty buffers when starting recording
immediately after initializing the stream. Which is one of the reasons I
initialize the stream on init instead of recording start.

**Comment by chris-rudmin** [comment]
Stream now stops when recording is finished.
