### ISSUE TITLE
best practices for handling initialization changes in v3+

### ISSUE THREAD

**Issue by hburgund** [chris-rudmin/Recorderjs#150]
I am upgrading from v2.1.2 and am encountering numerous small issues, most of which I have fixed easily, but I do have two outstanding questions:

* it seems there is no more `streamReady` handler(?); where do you recommend including code that I used to have in this spot? (enabling buttons etc)
* I see you have removed `initStream()`. Previously, I used the completion of `initStream` to trigger things (see below example of my code) and am wondering again what the best way would be to move this code somewhere else.
```
recorder.initStream().
    then((stream) => visualize(stream));
```

**Comment by chris-rudmin** [comment]
`initStream` was removed to aid in iOS implementations. The stream is instantiated on `start` so you should now do `recorder.start().then(() => visualize(recorder.stream));`
