### ISSUE TITLE
Not workin in Chrome

### ISSUE THREAD

**Issue by ebelendez** [chris-rudmin/Recorderjs#19]
Hi, I can't make the example work on Chrome, is it supposed to work on Chrome 43?
Is there any trick?

**Comment by chris-rudmin** [comment]
Works for me in Chrome 43 on mac.  What error are you getting?  FYI this script will not work if you are using file:/// to serve the html.  Try [this](http://rawgit.com/chris-rudmin/Recorderjs/master/example.html) and tell me if it works.

**Comment by ebelendez** [comment]
Thanks thats it! With FF it works online and offline but Chrome just online..
