### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by kentcdodds** [chris-rudmin/Recorderjs#20]
Could we get this on npm? If you're not familiar with how to do that, here are [some helpful instructions](https://gist.github.com/kentcdodds/4ed8489c2ff465635ce8)

**Comment by chris-rudmin** [comment]
Can you give me some good reasons to do this? I've got this in Bower already. Also, this lib only works on the client side and will not work with node.

**Comment by kentcdodds** [comment]
I, like many others, use npm for all frontend stuff. With popular tools like webpack and browserify, this is very easily accomplished and npm does a better job at encouraging good practices for modularity. There has been a big move in the community to make npm the standard for client-side libraries as well as tooling.

**Comment by chris-rudmin** [comment]
Sounds good. I don't have a good reason not to do this... 
Published as opus-recorder

**Comment by kentcdodds** [comment]
:+1: sweet! I can't wait to use this :)
