### ISSUE TITLE
recorder.dataAvailable firing immediately first time

### ISSUE THREAD

**Issue by DominicLee** [chris-rudmin/Recorderjs#24]
I have incorporated recorder.js into a Meteor project. Everything works fine (thanks!) but for some reason the first time I do a recording, it fires dataAvailable after only 130 bytes across both Chrome and FF (haven't tested on anything else yet). The second recording behaves as expected. Any reason why this might be happening?

**Comment by chris-rudmin** [comment]
Not sure. Can you get it to reproduce with the [example page](https://rawgit.com/chris-rudmin/Recorderjs/master/example.html)? What settings are you using?

**Comment by chris-rudmin** [comment]
If you have the page online somewhere, send me a link and I can take a look.

**Comment by DominicLee** [comment]
Aha! Front-end developer had it firing the click twice on the record button
:) Issue closed.

**Comment by chris-rudmin** [comment]
Solved!
