### ISSUE TITLE
Encoder postMessage transferables and syntax

### ISSUE THREAD

**Issue by Hengjie** [chris-rudmin/Recorderjs#25]
1. I think we should probably remove the extra semi-colon:

```
this.worker.postMessage( page, [page.buffer] );;
```

2. Detect if it supports transferables, and switch between `postMessage(object, transferableList)` and `postMessage(object)`

To test:

```
var ab = new ArrayBuffer(1);
worker.postMessage(ab, [ab]);
if (ab.byteLength) {
  alert('Transferables are not supported in your browser!');
} else {
  // Transferables are supported.
}
```

Source: https://developers.google.com/web/updates/2011/12/Transferable-Objects-Lightning-Fast

**Comment by chris-rudmin** [comment]
Which browser are you using that supports recording audio but not transferrable objects?

**Comment by Hengjie** [comment]
Chrome v15 introduced transferables while audio-api was introduced in Chrome v10.

**Comment by chris-rudmin** [comment]
All Chrome versions less than 30 account for less than 0.1% percent of market share. I'm not going to adjust code for a very small minority of people who don't let chrome auto upgrade.

Fixed the double semi-colon.
