### ISSUE TITLE
Document Decoder

### ISSUE THREAD

**Issue by chris-rudmin** [chris-rudmin/Recorderjs#26]
Add documentation on how to use oggopusDecoder

**Comment by mudcube** [comment]
This might not be very helpful. This takes a OGG blob and converts it into audio buffers:

```
var worker = new Worker('./oggopusDecoder.js')
worker.postMessage(recorder.config); // uses same config as for recording
worker.addEventListener("error", function(e) {
    console.log(e);
});
worker.addEventListener("message", function(e) {
    console.log(e.data);
});
///
var reader = new FileReader();
reader.onload = function(event) {
    worker.postMessage({
        command: "decode",
        pages: new Uint8Array(this.result)
    });
};
reader.readAsArrayBuffer(blob);
```

**Comment by chris-rudmin** [comment]
Thanks for the snippet. I have started an example in a seperate repo, but it's not complete.

**Comment by super-coder** [comment]
I am currently trying to use in an app, so what i need, seems very common - a user clicks **Record** on a page, if it's first time he is prompted for a authorization, if he chooses Allow, the recording starts. Then if he wants to record again, he doesn't have to init/authorize again. I am having difficulties how to get rid of **Init** button, which is not very useful in a real life app. any ideas? (And tons of thanks of course!)

**Comment by chris-rudmin** [comment]
@super-coder It was a conscious decision that the api is designed to make the recorder close the stream after finishing recording. We don't want the user to think we are eavesdropping by leaving the stream open. If you don't want to close the stream, you should use the pause function which will leave the stream open and continue recording when resumed.

**Comment by super-coder** [comment]
I see what you mean, not closing the stream actually leaves the red dot on Chrome tab. 
But can't the authorization be granted permanently? My users trust my app, they just want to press Record any time and record a memo. I would be forcing them to do two additional clicks every time - Init and Allow. Kinda not cool :)

**Comment by super-coder** [comment]
I figured out, for permanent permission, https is required, so ideally I want one button Record and it would ask for authorization and on success callback start recording. Then on Stop kill the stream. So in this case in a subsequent stream creation on https there won't be a authorization prompt. 
I think this is a typical business case

**Comment by super-coder** [comment]
is it possible to get access to wav blob? because ogg is not supported by Android Chrome from what i see? I could let user play wav but when saving, send compressed ogg

**Comment by chris-rudmin** [comment]
@super-coder I've removed comments unrelated to this issue. Please open a new issue if you have an issue or questions about the lib.

**Comment by brancusi** [comment]
Hi,

Would it be possible to outline how to go from encoded blob to playing back via a AudioContext destination? I would like to connect to a gain node and playback through there.

I have tried getting this example working as well as the other repo. I see the output from the decoder is a Float32Array is returned, what is the next step to get this actually playing though?

Thank you

**Comment by chris-rudmin** [comment]
The decoder returns an array of buffers (one for each channel)
- Configure the decoder to decode at your context sample rate using config option `{ outputBufferSampleRate : audioContext.sampleRate }`
- Store each buffer as it is decoded
- Create an audioContext buffer with appropriate length (number of decoded buffers * decoded buffer length)
- Fill audioContext buffer with decoded data
- Playback audioContext buffer
- Sample code at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer)

**Comment by brancusi** [comment]
Thanks @chris-rudmin, got it working!

This returns a promise and resolves with a source that can be started. A little lengthy but works for now. Does anything pop out at you as being a potential problem?

Thanks again for the great library!

```javascript
/**
   * Create a buffer source from an ogg blob
   * @param {Blob} The ogg blob created by recorderjs
   * @param {AudioContext} An instance of an AudioContext to create the bufferSource with
   * @param {Integer} Numbers of channels, defaults to 2
   * @returns {Promise} A promise that will resolve with an AudioBufferSourceNode prefilled with the ogg blob data, ready for playback
   */
  createBufferSource ( blob, audioContext, channels = 2 ) {
    return new Promise((res, rej) => {
      const decoder = new OpusDecoderWorker();
      const buffers = [];
      const config = {
        outputBufferSampleRate : audioContext.sampleRate,
        bufferLength : 4096
      }

      decoder.onmessage = e => {
        if (e.data === null) {

          var frameCount = buffers.length * config.bufferLength;
          var audioBuffer = audioContext.createBuffer(channels, frameCount, audioContext.sampleRate);

          // Fill the channel data
          for (let channel = 0; channel < channels; channel++) {
            var channgelBuffer = audioBuffer.getChannelData(channel);
            buffers
              .map((buffer, i) => {
                (buffer[channel] || buffer[0])
                  .forEach((frame, j) => {
                    channgelBuffer[(i*config.bufferLength)+j] = frame;
                  });
              });
          }

          const source = audioContext.createBufferSource();
          source.buffer = audioBuffer;
          source.connect(audioContext.destination);

          // Resolve the promise
          res(source);
        } else {
          buffers.push(e.data);
        }
      };

      // Initialize the decoder
      decoder.postMessage({ command: "init", config: config });

      // Load blob
      const reader = new FileReader();
      reader.onload = e => {
        decoder.postMessage({ command: "decode", pages: new Uint8Array(reader.result)});
        decoder.postMessage({ command: 'done' });
      };
      reader.readAsArrayBuffer(blob);

    });
  }
```

P.S. This is working in a react app using the worker-loader to wrap the worker scripts in case anyone wonders about that new worker line.

**Comment by chris-rudmin** [comment]
@brancusi Looks good. What language are you writing in? Does defining a value as const make it immutable? Seems strange to make an array which you push to a constant.

**Comment by brancusi** [comment]
@chris-rudmin ok cool. Yes this is es6 syntax. The `=>` is a new way to declare an anonymous function that will bind any `this` references to current outer scope. Gets us away from having to do, `var self = this;`

As for [Const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const), it just makes the reference read-only but you can still mutate the underlying array in our case. I think it adds some clarity of intend mostly, none of the refs will be redeclared inside that promise.

Under the hood right now this all gets compiled to es5 any way, so const become var. [Babel](https://babeljs.io/repl/)

**Comment by chris-rudmin** [comment]
@brancusi One thing I might add, you could get a higher fidelity playback if you can create the buffer source at with a sample rate of 48000. This is the native decoder rate of opus and it will avoid you using my lo-fi resampler.

**Comment by brancusi** [comment]
Thanks @chris-rudmin, I will definitely swap that out. Will it matter if the audioContext's rate is different? Or should that be set (can it be set?) before hand to 48000 as well?

**Comment by chris-rudmin** [comment]
My understanding is that it will use the browsers internal resampling algorithm which should be faster and of higher quality than a resampler implemented in js. However I have not tested this.

**Comment by chris-rudmin** [comment]
Added a decoder example in the examples folder!
