### ISSUE TITLE
Android Chrome mobile doesn't play the recorded file

### ISSUE THREAD

**Issue by diegomesata** [chris-rudmin/Recorderjs#28]
Hello, I'm testing the example on Chrome mobile Android 5.0, it records ok, but I can't play the recorded file. 

According to this doc http://developer.android.com/guide/appendix/media-formats.html .ogg files can be played on android. 

Do you have any idea?

Thank you

**Comment by chris-rudmin** [comment]
The page you linked says android 5+ supports opus in an mkv container. I am
returning opus in an ogg container.

**Comment by chris-rudmin** [comment]
To make playback work, you could decode the file using oggopusDecoder.js and playback the raw PCM.

**Comment by alexthewilde** [comment]
@chris-rudmin I've been trying to make this work using oggopusDecoder.js as you suggested, but with no success. Could you provide a small example how this could be achieved in combination with an `<audio>` tag? That'd be absolutely fantastic.

**Comment by chris-rudmin** [comment]
@alexthewilde To playback in an `<audio>` tag, will be multi-part process:
1. Decode the audio using the decoder
2. Convert Float32 PCM to INT16 and put into WAV RIFF container
3. Playback wav blobURI in audio tag. 

I'll try to post some code samples later on when I get some time.
If you don't need the audio tag, it will be simpler to playback from audio buffers using the web audio API.

**Comment by alexthewilde** [comment]
@chris-rudmin I've been researching this issue a bit more and found [hpr.dogphilosophy.net/test/](hpr.dogphilosophy.net/test/). This test shows that `.ogg` generally works natively on Android/mobile Chrome, i.e. without being in a `mkv` container.

Please have a look at this demo: [http://jsfiddle.net/pm84nsdh/3/](http://jsfiddle.net/pm84nsdh/3/)
The second audio example has been created using your Opus Recorder and it unfortunately doesn't play back in mobile Chrome. As you can see both files are served from the same server and have proper perms etc.

Can you spot any difference in these two ogg files which causes the one to play but not the other?

**Comment by chris-rudmin** [comment]
Yes, the difference is the other file is Vorbis encoded audio. The file I encode is Opus encoded. Ogg is just the container.

**Comment by alexthewilde** [comment]
@chris-rudmin thanks for clarifying! I'm assuming there's no way to encode in Vorbis using your library, is there?

**Comment by chris-rudmin** [comment]
@alexthewilde Don't despair though, decoding the ogg is not hard. I'll try and post an example tonight.

**Comment by chris-rudmin** [comment]
Made an example page to decode the file to wav audio. Hope this helps

https://github.com/chris-rudmin/DecodeToWav
http://rawgit.com/chris-rudmin/DecodeToWav/master/example.html

**Comment by alexthewilde** [comment]
@chris-rudmin that's super helpful, cheers! I guess I can make it work from there.

**Comment by chris-rudmin** [comment]
@alexthewilde if you are reading the file from the server I think you can do it like this to get an arraybuffer:
```
var oReq = new XMLHttpRequest();
oReq.open("GET", "/myfile.ogg", true);
oReq.responseType = "arraybuffer";
...
```

**Comment by diegomesata** [comment]
How may time can you record in android chrome? I record about 10s and the browser crash down!

**Comment by chris-rudmin** [comment]
@diegomesata Never tried in mobile.  I would assume you are limited by device resources (memory). If you are saving the file to the server in the end, you could try and stream the data as it is encoded instead of storing locally. To do this, you should override `recorder.onPageEncoded()`

**Comment by chris-rudmin** [comment]
@diegomesata If you could leave me a stack trace, or whatever error you get, it might be helpful. Perhaps it is something we can fix.

**Comment by diegomesata** [comment]
@chris-rudmin today browser doesn't crash down, sorry for the false alarm. At server side what library could I use to decode the ogg to wav?

**Comment by chris-rudmin** [comment]
@diegomesata Personally, I like [sox](http://sox.sourceforge.net/). I think you can run command line stuff in c#.  If so you also have the choice of [opus-tools](https://www.opus-codec.org/downloads/).

**Comment by diegomesata** [comment]
Thank you for all your help, opus-tools converts the file to wav without problem, but with sox I got: sox.exe FAIL formats: no handler for detected file type `opus'
