### ISSUE TITLE
Merge opus files in js

### ISSUE THREAD

**Issue by diverted247** [chris-rudmin/Recorderjs#29]
Apologies in advance for posting this as an issue.

We are using Recorderjs to encode to opus and the library is working great. We have a need to merge opus encoded files(identically encoded) on server in nodejs like so: file1.ogg + file2.ogg + ... fileN.ogg = final.ogg

The work would be paid but I would prefer final work be open source and in your name.

email: ted@light.ly

Thanks,
Ted Patrick

**Comment by chris-rudmin** [comment]
Hi Ted,

Unfortunately for me, I don't think there is any work to do. :) Ogg files support chaining, so you can [concatenate the files safely](http://www.xiph.org/vorbis/doc/oggstream.html). It might be required that you make sure the serial number for each stream is unique (from my encoder it is not)

**Comment by chris-rudmin** [comment]
Reading [here](https://wiki.xiph.org/OggOpusImplementation), it is possible that some players don't support chained files. If this is the case and you have lots of server cpu cycles and memory, I would suggest you decode and re-encode the opus files to get one large file.

**Comment by diverted247** [comment]
Chris, the decode and encode server side was the item I wanted to avoid if possible. Was hoping this was removing the OGG data, taking OPEN samples glueing them together and appending new OGG data. Obviously that would be far faster and a straightforward task with node file streams. One reason we want to use OPUS is quality/compression ratio for spoken audio is so high. Again would be more than happy to fund this work open source if you were up to it. Thanks for the context and details.

**Comment by chris-rudmin** [comment]
@diverted247 Unfortunately you cannot glue the opus packets together as the decoder is stateful and depends on the output of the previous packets to decode properly. Concatenating the ogg files would be your best option. Let me know if that suits your purpose.

**Comment by chris-rudmin** [comment]
@diverted247 I've just made some tweaks to support chaining ogg files in v0.4.3

**Comment by diverted247** [comment]
Thanks Chris.
