### ISSUE TITLE
Is it possible to use lower sample rates like 8000Hz

### ISSUE THREAD

**Issue by ajithreddy** [chris-rudmin/Recorderjs#3]
Is it possible to use lower sample rates like 8000Hz?
I know you have forced the use of 48000Hz sample rate, but is there any way I can make it convert to .ogg at 8000Hz sample rate??

**Comment by chris-rudmin** [comment]
The opus encoder requires audio at 48000 Hz to work. If you don't want content above 4000 Hz, you could downsample, and then upsample before sending to the encoder.

There is also an option in oggopus.js which I have not exposed which is encoderApplication.  You can set this to 2048 to limit the bandwidth but I have not tested this.

**Comment by chris-rudmin** [comment]
The opus encoder docs are [here](http://www.opus-codec.org/docs/html_api-1.1.0/group__opus__encoder.html). I see there is an option to change the encoder bitrate. You could try experimenting with that. Let me know your results.

**Comment by chris-rudmin** [comment]
As of commit 1f91afc I have enabled encoding different sample rates. Also included is a better resampler without glitches at the buffer boundaries.

**Comment by ajithreddy** [comment]
Thanks a lot for the quick support. It is working great!!!
