### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by chris-rudmin** [chris-rudmin/Recorderjs#35]
Resampler, encoder and decoder would benefit greatly from unit tests.

**Comment by Rillke** [comment]
Just keep in mind to specify a fixed stream serial number for a deterministic result.

**Comment by chris-rudmin** [comment]
@Rillke good thinking :) I haven't quite got there yet.

**Comment by chris-rudmin** [comment]
Unit tests are in place. Code coverage will improve with time.
