### ISSUE TITLE
Issue with data/seek in ogg Blob? (updated)

### ISSUE THREAD

**Issue by JeremyHargis** [chris-rudmin/Recorderjs#36]
Hi, Chris.

First off, thanks for your work on this. I think it will be very helpful for a project I am working on. My JS abilities are pretty terrible, but I'm trying to upload a recorded .ogg file as a blob to a server (running PHP). I am listening for the `dataAvailable` event and trying to append `e.detail` to a form, which I am hoping to POST through Ajax. I am finding that the resulting .ogg file is always the same size (130k) and never seems to have any actual captured audio when I try to play it back. The actual recording portion seems to be working (I am prompted for permissions to the mic, etc...). I am sure I am missing something obvious and I hope you can point it out to me.

Here my simple listener setup:

```javascript
recorder.addEventListener( "dataAvailable", function(e) {
        var formData = new FormData();
        formData.append('audio', e.detail, 'blob.ogg');
        console.log('about to send');
        $.ajax({
            type: "POST",
            url: '/url',
            data: formData,
            success: function(data) {
                console.log('success!');
            },
            processData: false,
            contentType: false
        });
    });
```

Thanks for your help on this.

**Comment by JeremyHargis** [comment]
I must have been doing something because it's working now and I'm not sure why. Sorry for cluttering your issue log!

**Comment by JeremyHargis** [comment]
I'm sorry, but it appears I do have an issue here. When I upload files using the code I show above, the files seem to be corrupt somehow. I can play the files back successfully, which is great, but no matter which software I use (ffmpeg/ffplay, vlc, Firefox, Chrome, etc...), I cannot seek to different points in the file. It is like some kind of index is being lost or something. Have you seen this before? When try your hosted example, I see that the files are completely seekable within the browser, so I know something must be wrong on my end.

**Comment by chris-rudmin** [comment]
You can validate if there are problems with the file using [opusfile](https://www.opus-codec.org/downloads/).

Which browser/OS are you using for encoding?
Some issues I have encountered are related to browser and samplerates.  For example, Firefox (mac) will not send data if sample rate is above 16/44.1. I would try setting your system and soundcard sample rate to 16/44.1 and then restart your browsers, and see if it makes a difference.

**Comment by JeremyHargis** [comment]
Chris,

Thanks for your advice. I installed opus-tools and went to test using both Chrome and Firefox. Both magically worked. This makes me wonder if I was possibly missing some dependency that was met when I installed opus-tools. Is this possible? I am testing this on a laptop running Arch Linux.

**Comment by JeremyHargis** [comment]
Update: I guess it's hit or miss because sometimes it is still having the seek issue. For example, I just encoded an opus file using the library in Chrome. In Chrome, seek does not work and it does not show any progress while playing the file (even though it DOES play the audio). In Firefox, seeking and progress work. In VLC, seeking and progress do not work (even though the audio plays). Strange! Here is the output of Opusinfo for this file:

```
jeremy ~/webdev-projects/project1/public/storage/audio $  opusinfo 1_172_0913f2d5aa.opus
Processing file "1_172_0913f2d5aa.opus"...

New logical stream (#1, serial: 65a1b76d): type opus
Encoded with Recorder
Opus stream 1:
        Pre-skip: 3840
        Playback gain: 0 dB
        Channels: 1
        Original sample rate: 44100Hz
        Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
        Page duration:   3720.0ms (max), 3375.6ms (avg),  660.0ms (min)
        Total data length: 196903 bytes (overhead: 0.945%)
        Playback length: 0m:30.300s
        Average bitrate: 51.99 kb/s, w/o overhead: 51.5 kb/s
Logical stream 1 ended
jeremy ~/webdev-projects/project1/public/storage/audio $ 
```
Let me see what happens if I adjust the bitrate, per your comment...

**Comment by JeremyHargis** [comment]
I tried manually setting bitRate and encoderSampleRate like this:

```javascript
    recorder = new Recorder({
        bitRate: 16,
        encoderSampleRate: 24000,
        encoderPath: "{{ asset('/js/ogg/oggopusEncoder.js') }}"
    });
```

Now, although the files seem to have data, playing them back produced no audible sound.

**Comment by chris-rudmin** [comment]
@JeremyHargis, bit rate is target bits/second. For some reference, a low quality mp3 is encoded at 196608 bits/s or 192 kbps. I imagine 16 bits/s is much to low to encode anything.

**Comment by JeremyHargis** [comment]
Thanks for your feedback. That was my mistake. :) I don't know much about audio recording! Anyway, as others aren't complaining of this and it does work some of the time, I'm going to close this issue.
