### ISSUE TITLE
Dropped data?

### ISSUE THREAD

**Issue by lepinsk** [chris-rudmin/Recorderjs#37]
Hey Chris,

I'm wondering whether you've ever seen an issue where audio data seems to get lost in a file without getting encoded. I'm not quite able to duplicate, but I have a hunch that it's related to underpowered/overtaxed systems. It doesn't seem to affect the overall file-length, but sections where there *should* be audio captured have silence instead. ```opusinfo``` doesn't seem to reveal anything off with the files produced at the other end.

Anyway, I've been looking into this and figured I'd check to see whether it's something you've experienced.

**Comment by chris-rudmin** [comment]
I've not done extensive testing (no mobile testing), but I recall on my mac if I switch the system bitdepth/sample rate without restarting the browsers, the data buffers provided by the browser are empty. 

I've also noticed that firefox mac will provide empty data buffers when configured at high bitdepth/samplerate ex 24/96 or 24/192.

I think you could eliminate this as a cause if you set the system rates to 16/44.1 and restart all browsers.
Would be good to identify the browser and OS, to help diagnose encoding issues. Some bleeding edge browser versions might only partially support the required APIs etc.

**Comment by lepinsk** [comment]
Hmm, interesting.

I should have probably included a bit more context. In my case, *all users* are in Chrome on Windows or Mac (and within a pretty tight range of Chrome versions). In the case of lost audio, the user's recording is *mostly* complete, but there are a few dropout sections where there's, say, 2s of silence in the middle of a sentence.

**Comment by chris-rudmin** [comment]
By the sounds of the problem, it is the browser providing empty data buffers. I can't say I've experienced this before, but you could try to increase the bufferlength to 8192 or higher. This will increase the stream delay, but will give more time for the system to handle buffering/resource constraints.

**Comment by chris-rudmin** [comment]
Another though occured to me, that the event publish we are doing when receiving a buffer might not be a real async event (to be investigated). Are you doing any UI or resource intensive tasks on the event publish of 'duration'?

**Comment by lepinsk** [comment]
Hmm, that's an interesting theory. In our case, we have a webrtc voip session happening in parallel with recorderjs encoding audio data. Recorderjs spits out data that we accumulate into 500kb chunks and upload every so often.

I've confirmed that in at least one case, the users heard the same audio dropouts over their voip session, so it sounds like (as you first suggested) the browser is providing empty data buffers to both the webrtc apis and recorderjs...

**Comment by chris-rudmin** [comment]
@lepinsk Are you still experiencing audio dropouts after increasing the bufferLength?

**Comment by lepinsk** [comment]
@chris-rudmin It's hard to tell – the issue was cropping up very intermittently before so I'm having trouble reproducing it (with or without the change). I'm going to keep at it and I'll let you know what I figure out.

**Comment by lepinsk** [comment]
@chris-rudmin I fear that this is a stupid question, but I'm trying to wrap my head around the potential downsides of a larger ```buggerLength```. 

When you refer to an increased stream delay, I'm taking that to mean the algorithmic delay from sound produced → opus data encoded (which, right now, is super fast). I can't imagine the increased buffer length would change this by more than a few seconds, would it not?

**Comment by chris-rudmin** [comment]
@lepinsk The `bufferLength` changes the amount of audio data collected before it passes to the audio node and to the encoder. The larger the bufferlength means the longer it takes to fill up.  This means It gives us more time to process the audio, but it takes longer to arrive.
It could be detrimental in the situation where you want to have a live phone conversation or music synchronization and any additional ms delay would affect the quality of the communication by being too slow.

For a mono stream at 16/44.1, a 4096 byte audio buffer would be 4.6ms of audio (this would be the minimum latency we could achieve). by doubling the buffer to 8192 we would add 4.6ms of additional latency to the whole process. For a phone call, about 100ms of latency starts to make communication awkward.

**Comment by lepinsk** [comment]
@chris-rudmin Thanks for the reply – that's how I understood this to work.

In my case I've got a WebRTC audio call going on in tandem with this, but that's independent of any of this stuff – I'm using Recorderjs solely to generate a recording for playback later; the latency is of no concern whatsoever.

**Comment by chris-rudmin** [comment]
@lepinsk The idea behind increasing the bufferLength is that we trade CPU cycles for memory and latency. So if the dropped audio is because of CPU overload, it might be one way to relieve some pressure.

**Comment by lepinsk** [comment]
Thanks so much for all the info here. If there are any further issues with this, I'd expect they're well outside of the scope of Recorderjs. I'm closing up this issue.

**Comment by lepinsk** [comment]
Hey Chris,

Looks like we're still seeing this crop up very infrequently on underpowered systems (primarily Chromebooks, it seems), even at a (max, as far as I can tell) buffersize of ```16384```. What I'm presuming is happening when the system becomes overtaxed is that a new ```onaudioprocess``` event fires before the previous one completes, which I guess just turfs the previous in progress event?

What's strange is that we seem to lose big gulps of time – 1000ms – but only very infrequently, say every few minutes. (Though I suppose that could correspond to some big transient event like a GC that prevents any and all ```onaudioprocess``` events from completing while it's happening.)

We're trying to figure out the best way to work around it. The first thing that comes to mind is adding some sort of timestamp (beyond the granule position) in metadata to the ogg pages, but that doesn't seem particularly easy to do, since those get written out on the other end of the encoder which is both asynchronous and (as we've seen above) sometimes is missing data.

Anything I might be missing?

**Comment by chris-rudmin** [comment]
I have another theory that might explain what is happening. Perhaps the process audio events are building up faster than they can execute and at some point the stack gets too large and the tab clears all the events built up in the queue (lost audio). This might be testable using a resource limited virtual machine.

If this is the case, I don't know what the solution is other than make event processing less intensive. This could be done by:
- Try using the encoder application option restricted low delay `{encoderApplication :2049}` which will yield lower quality but faster performance for encoding.
- Reducing the bit-depth or bit-rate of the source audio context (not sure if this is possible in your case)
- Remove any resampling done by the RecorderJS lib.  This will remove audio filters which are processing the audio before it arrives at the worker and will remove resampling done inside the worker.

**Comment by lepinsk** [comment]
Thanks for your thoughts – it sounds like that's very possibly what's going on. I've looked closely at how ```onaudioprocess``` is running with an eye to removing the efficiency – I wonder whether using ```postMessage```'s ```transferList``` param might speed things up a bit (transferring ownership of the ArrayBuffer as we pass send it off to the worker), but so far no luck.

I'll keep tinkering and let you know if I figure out anything on my end. As always, I appreciate your help.

**Comment by chris-rudmin** [comment]
I've tried to pass the ownership of the buffer when passing it to the
worker, but I did not have any luck. I presume that the `onaudioprocess`
needs to maintain control of the buffer for playback of the audio (even
though we don't use this buffer for audio playback).

**Comment by chris-rudmin** [comment]
I've also had the idea to replace my resampler with the speex reampler (compiled with emscripen) it should provide better quality and perhaps using asm.js will improve the performance as well.

**Comment by chris-rudmin** [comment]
I'm also sure there are places to improve memory usage by reusing data buffers instead of copying into new ones.

**Comment by chris-rudmin** [comment]
Also if you check into the resampler code in git history, you could try using my linear resampler instead of 3-tap resampler. It should reduce the number of computations required by more than 2/3.

**Comment by chris-rudmin** [comment]
https://github.com/chris-rudmin/Recorderjs/blob/1d134047f0721728a2c0fa2a8d0847e5349ed4e2/wavepcm.js#L118

**Comment by chris-rudmin** [comment]
@lepinsk Not sure if you are still investigating this, but I have a new branch using the speex resampler. https://github.com/chris-rudmin/Recorderjs/tree/speexdsp. It has configurable resampling quality `{ resampleQuality: 5`. In general there should be less data copying and less garbage cleanup in this version. Also file sizes are smaller. I'm not quite sure how to benchmark the two to compare them. If you have some ideas how to do this, i'm open to suggestions :).

**Comment by lepinsk** [comment]
@chris-rudmin Hmm, that's a good question. I haven't come up with a great way to trigger this – though the increased buffersize seems have to alleviated the problem. In situations where it occurs, it seems to happen *much* less frequently – I think your hunch about clearing the stack once it becomes too large is probably what's going on here.

If the issue is one of the encoder being unable to get everything done in realtime, perhaps timing the delta between recording stop and encoder complete for same-length recordings could give us some idea of how well the encoder is keeping up with the workload... (Of course, this goes out the window if the encoder's workload depends heavily on the input, or this is caused by transient CPU/mem usage by other uncontrolled stuff.) Might be worth a look anyway, tho?

**Comment by lepinsk** [comment]
... so this is crazy naïve, but I wrapped the linear and 3-tap resamplers in 

```js
var rsLog = "resampler rnd=" + Math.random();  //making sure each timer has a unique name
console.time(rsLog);

[...]

console.timeEnd(rsLog);
```

Here's a handful of timer logs from the two. Perhaps a similar technique would would to give a rough idea of the efficiency gain on the speex resampler?


3-tap | linear
-----|-----
5.417ms | 3.289ms
10.491ms | 5.718ms
11.890ms | 2.662ms
10.091ms | 2.279ms
10.328ms | 2.367ms
15.346ms | 6.410ms
8.902ms | 2.887ms
10.303ms | 2.368ms
11.936ms | 2.160ms
9.936ms | 2.668ms
12.939ms | 2.696ms
10.471ms | 2.244ms
15.177ms | 2.171ms
22.183ms | 7.088ms
14.789ms | 2.530ms
14.964ms | 2.528ms
20.695ms | 2.259ms
15.408ms | 2.416ms
14.264ms | 2.835ms
14.514ms | 2.286ms
16.710ms | 2.455ms
14.470ms | 2.457ms
13.423ms | 2.538ms

**Comment by chris-rudmin** [comment]
It's a bit more complex than that because I have added a 3 pole filter in the audio chain in recorder lib for my homemade resampler. Speex does the filtering internally, so to properly compare them we would need to test the whole flow from audiocontext init until data output.

**Comment by lepinsk** [comment]
Hm, right. I ran a cursory test on ```master``` vs the ```speexdsp``` branch to watch the time between ```recorder.stop();``` and ```dataAvailable```, but I don't think I'm getting anything useful there if my test machine isn't having trouble keeping up with the encoding task to begin with. Perhaps a more meaningful result if I can track down a user who has had problems with this...

**Comment by chris-rudmin** [comment]
Just added two branches for master and speex with naive benchmarking. Will collect some CPU profiles while they are running and see what comes out.

**Comment by chris-rudmin** [comment]
<img width="2073" alt="master" src="https://cloud.githubusercontent.com/assets/506755/13095661/80ee7b72-d4e1-11e5-8c12-8bffd2c0f77e.png">
<img width="2072" alt="speex" src="https://cloud.githubusercontent.com/assets/506755/13095662/80eff146-d4e1-11e5-878c-9cb81f216dd8.png">

My machine performs both about equally fast, what is more interesting is the heap graph. The speex branch seems more memory stable.  Resampler was resampling from 96k to 48k

**Comment by chris-rudmin** [comment]
BTW I couldn't figure out how to collect CPU profile of the main thread as well as the worker. If you know how, could you fill me in?

**Comment by lepinsk** [comment]
Sorry, not quite sure how to do that myself. :-/

**Comment by chris-rudmin** [comment]
Also Garbage collection on speex branch occurs a magnitude less than on master (~1/10th)

**Comment by lepinsk** [comment]
Oh wow – that's interesting. And this is with comparable resampling quality?

**Comment by chris-rudmin** [comment]
The resampling quality should be better with speex because of their higher quality filter. I was able to get a CPU profile from inside the worker (but not of exactly the same lengths). It seems speex at quality 0 which is comparable to my resampler runs about 5% faster. Speex at quality 3 runs about 4% slower than my resampler.  This result is just from one test approximately 10 seconds long.

**Comment by chris-rudmin** [comment]
I will likely do some more testing and then merge this into master.

**Comment by chris-rudmin** [comment]
Marking as resolved. Please re-open if you are still encountering issues.
