### ISSUE TITLE
Why using web workers and not ScriptProcessorNode?

### ISSUE THREAD

**Issue by mitar** [chris-rudmin/Recorderjs#39]
Why this is not implemented using Web Audio API and encoding in the [ScriptProcessorNode](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode)?

**Comment by chris-rudmin** [comment]
@mitar The encoding is implemented using the WebAudio API and the encoding is done in a ScriptProcessorNode. Maybe you mean why aren't we using a Audio Worker? If that is your question, it is because there is no browser support for this feature yet.

**Comment by mitar** [comment]
Hm, I saw that you call [new Worker](https://github.com/chris-rudmin/Recorderjs/blob/master/recorder.js#L150) and I assumed things are done there? Are you saying that then inside the worker you use `ScriptProcessorNode`? I do not see where you would use it [here](https://github.com/chris-rudmin/Recorderjs/blob/master/oggopusEncoder.js)?

But I see, so you use `ScriptProcessorNode` but then you call into the web worker to do the real encoding. Interesting.

So what I am worrying here is that by using web workers to do the work it is unclear what happens if the tab goes into the background. It might slow down the web worker and then encoding could lag? This is just speculation though.

**Comment by chris-rudmin** [comment]
@mitar encoding is done asynchronously on purpose so that it could lag. This allows ScriptProcessorNode to finish quickly to allow the next buffer with dropping any data. This way, slow encoding is not an issue as it will finish eventually and then your recording is ready.

**Comment by mitar** [comment]
Interesting idea. Thanks for explanation.
