### ISSUE TITLE
Audio skipping

### ISSUE THREAD

**Issue by afonso-arantes** [chris-rudmin/Recorderjs#40]
Hi Chris,

I'm using your library in my application to encode voice recordings from a microphone/headset combo. One of the recordings has some strange looping/skipping artifacts in it. The code used to init the recorder is:

var MONITOR_GAIN = 0;
var NUMBER_CHANNELS = 1;
var ENCODER_SAMPLE_RATE = 48000;
var BIT_RATE = 64000;

var recorder = new Recorder({
        monitorGain: MONITOR_GAIN,
        numberOfChannels: NUMBER_CHANNELS,
        bitRate: BIT_RATE, 
        encoderSampleRate: ENCODER_SAMPLE_RATE,
        encoderPath: '/js/recorder/oggopusEncoder.js'
});

The code does a recorder.initStream(), followed by recorder.start() and recorder.stop()
I've recorded several audio files and only one had a problem.

This was done on Chrome Version 47.0.2526.80 m on Windows 7. The machine is under fairly high CPU load and sometimes the gui becomes unresponsive. Might this have anything to do with the problem?

The actual ogg file can be found at https://github.com/afonso-arantes/issue It's the only file in the repository but happens to be named 1449866949-gQIPhRPDyA3Cn2vyW8vs.ogg

Playing it inside the github site as raw doesn't seem to work, but it works if you download it using git or wget.

Thank you so much for your help.

**Comment by chris-rudmin** [comment]
@afonso-arantes I've experienced your same problem on high CPU load. The audio process does not have time to refill the audio buffer with new audio so you are left with the old one. One thing you can try is to Increase the `bufferLength`. The next size up is 8192.

**Comment by afonso-arantes** [comment]
Ok, I'll try increasing the buffer length and see whether that improves things.
