### ISSUE TITLE
Getting "Uncaught TypeError" with Chrome 47

### ISSUE THREAD

**Issue by JeremyHargis** [chris-rudmin/Recorderjs#41]
Hi, there.

I tested a known-working page using your library on Chrome 46 and it worked. I then upgraded Chrome to 47 and tested again and got this exception:

```
Uncaught TypeError: this.stream.stop is not a functionRecorder.clearStream
@ recorder.js:51Recorder.stop
@ recorder.js:186(anonymous function)
@ audio:461m.event.dispatch
@ jquery.js:4r.handle @ jquery.js:4
```

Happens on Chrome 47.0.2526.106 on both Windows and Linux, both 64 bit. The same code still works fine on Firefox on Windows and Linux.

**Comment by Rillke** [comment]
Did you fetch and apply 481544e6a29af7a8712ddc57b8c24c5d8c11898b ?

**Comment by JeremyHargis** [comment]
@Rillke, yes, that fixed it. Sorry, I thought I had already brought in the latest changes. Thanks for your help!
