### ISSUE TITLE
example.html and js not running in chrome 

### ISSUE THREAD

**Issue by thesugarrush** [chris-rudmin/Recorderjs#43]
Hello,

I apologize if this is turns out not to be a real issue. I tried to use the example.html in Chrome but when I pressed the 'init' button, nothing happen.
In firefox, the getusermedia bring up a pop up and asking permission to access mic. That is expected behavior. 
Anything I need to do to make this work in Chrome? Thank you in advance.

**Comment by Rillke** [comment]
Did you [try it online](https://rawgit.com/chris-rudmin/Recorderjs/master/example.html)? Which version of Chrome on which operating system? Chrome 47.0.2526.106 appears to work, although it said I granted permission for the site despite I could not remember I did this and started recording right away after pressing init without prompting.

**Comment by Rillke** [comment]
Perhaps you are suffering from [SO: Chrome getUserMedia Not Requesting Permission Locally](http://stackoverflow.com/questions/13723699/chrome-getusermedia-not-requesting-permission-locally)?

**Comment by thesugarrush** [comment]
Rillke,

I tried the online version (https://rawgit.com/chris-rudmin/Recorderjs/master/example.html) per your suggestion, and it does work using my Chrome, version Version 47.0.2526.106 (64-bit) as of Jan 8th, 2016.

I also tried the example.html by creating a local web server per the stackoverflow link you gave me. I am using Nginx and it works as well using both Chrome and Firefox.

However, I tried using the  file:/// method in Chrome with no file server and the example *does not* work. I follow the suggestion to use the '--allow-file-access-from-files' generic when invoke Chrome from terminal and it does not solve the problem. So, for me, to make the example works in Chrome, I do have to create a local webserver for it. 

Hope this may be helpful for everybody else facing same 'issue'.

You're welcome to confirm the above.....or I can close this issue if it is not necessary to be confirmed, I guess?
Thanks.

**Comment by Rillke** [comment]
- Before running Chrome, make sure there are no chrome processes running
- Windows: `-allow-file-access-from-files`
- Other: `--allow-file-access-from-files`

[source](http://stackoverflow.com/a/5835359/2683737)

**Comment by thesugarrush** [comment]
Rillke,

This works for me! Now I am able to run the example using Chrome. Thanks for your help. I am closing this issue.

<quote>
**Before running Chrome, make sure there are no chrome processes running**
Windows: -allow-file-access-from-files
Other: --allow-file-access-from-files
</quote>
