### ISSUE TITLE
How to merge two recording

### ISSUE THREAD

**Issue by vtournel** [chris-rudmin/Recorderjs#44]
Hi, 

    I use your library successfully. It works really well. My goal is to achieve a complete recorder/player.
    I would like to insert an ogg file in another ogg file at a specific position. And this in the browser in javascript. So the user will be able to take an existing recording, and to insert a new recording in it. Do you think it is possible ?

   All the best,

Vivien TOURNEL

**Comment by chris-rudmin** [comment]
@vtournel Anything is possible if you put your mind to it! :) You won't be able to splice one ogg into another, but what you can do is decode both ogg files, splice the PCM data together and then re-encode the whole thing.

**Comment by vtournel** [comment]
Ok thanks a lot, i see how to do that, wanted just to be sure there was not a way to do it directly on the compressed version of that data. 

all the best,

Vivien TOURNEL
