### ISSUE TITLE
TrackStartError in Chrome v50

### ISSUE THREAD

**Issue by lepinsk** [chris-rudmin/Recorderjs#49]
Looks like Chrome's changed something in v50 (currently in beta) that is causing the ```navigator.getUserMedia``` call [in recorder.js](https://github.com/chris-rudmin/Recorderjs/blob/master/recorder.js#L110-L111) to throw an error. (Specifically, a ```TrackStartError```.)

It seems that this due to the parameters passed in the call – the call, as is, is 

```js
  navigator.getUserMedia(
    { audio : this.config.streamOptions },
```

However changing it to this

```js
  navigator.getUserMedia(
    { audio : true },
```

resolves the issue. 

I'm not sure what the implications of dropping the various options (```googAutoGainControl```, etc) are, so I haven't done this up as a PR, but I wanted to give you a heads up.

**Comment by chris-rudmin** [comment]
Thanks for the heads up.  I'll take a look at it when I have some time.

**Comment by chris-rudmin** [comment]
@lepinsk Just tested against Chrome v50.0.2661.75 (64-bit) and couldn't reproduce your error.  Can you add some more details about version and OS?

**Comment by lepinsk** [comment]
@chris-rudmin Looks like Chrome made some changes between the beta and now that have resolved the issue. I'm not seeing it happening in v50.0.2661.75 either. ¯\_(ツ)_/¯
