### ISSUE TITLE
speex_resampler_process_interleaved_float question

### ISSUE THREAD

**Issue by jamessetaro** [chris-rudmin/Recorderjs#51]
Hey Chris, I really **love** the work you did here with the opus encoder.  I was looking at doing something similar for actionscript. One question I have is, why do you use the _speex_resampler_process_interleaved_float when encoding opus?  For my purposes I don't really need more than 1 channel, am I right to assume this might not be necessary if you only have 1 channel?

if ( this.resampleBufferIndex === this.resampleBufferLength ) {
      _speex_resampler_process_interleaved_float( this.resampler, this.resampleBufferPointer, this.resampleSamplesPerChannelPointer, this.encoderBufferPointer, this.encoderSamplesPerChannelPointer );
      var packetLength = _opus_encode_float( this.encoder, this.encoderBufferPointer, this.encoderSamplesPerChannel, this.encoderOutputPointer, this.encoderOutputMaxLength );
      this.segmentPacket( packetLength );
      this.resampleBufferIndex = 0;
    }

**Comment by chris-rudmin** [comment]
The audio samples will be interleaved if there is more than one channel. See how the interface is initialized [here](https://github.com/chris-rudmin/Recorderjs/blob/master/src/encoderWorker.js#L203). If there is only one channel the audio will still be resampled appropriately.

**Comment by chris-rudmin** [comment]
If you were asking about whether you require resampling, the answer is yes it is required even with one channel.

**Comment by jamessetaro** [comment]
Thanks Chris.  And thanks again for the great lib!

Yea, I am totally new to this library.  Could you help me understand what it does and why you chose it to use it?

I was looking through the opus source and I didn't see it in the the examples they had posted, but maybe its to normalize for the case where recording can be coming from different samples(or maybe I just missed it)?

**Comment by chris-rudmin** [comment]
@jamessetaro The opus lib supports sample rates of 48000, 24000, 16000, 12000, 8000. If your input sample rate is guranteed to be one of those rates, then you dont need a resampler.  However most PCs and phones operate at redbook standard 44100 Hz. In this case you will need to resample to one of the supported sample rates.

**Comment by jamessetaro** [comment]
Thanks Chris, makes total sense now.
