### ISSUE TITLE
Encoded files can't be decoded by node-opus

### ISSUE THREAD

**Issue by Robbson** [chris-rudmin/Recorderjs#52]
Hello,

I'm trying to send the encoded ogg-opus files to a node server for decoding using the package node-opus which also handles the ogg container using node-ogg. 
Unfortunately node crashes. The output of the format event seems also to be weird because it's showing always 44100Hz, that is not supported by opus, independent from my chosen encoder settings on the client.

After some investigation I noticed that the libopus version of node-opus was pretty old (1.1 Beta).
So I replaced it using the current 1.1.2 build. Now it doesn't crash anymore but there is still no decoded data. And the weird 44100Hz are still shown as format.

If you use the opusinfo command line tool you can also see those 44100Hz. By the way opusdec tool plays the ogg-opus file successfully but it also shows several errors before ("Error playing audio").

It can be easily tested using your encoder example (recording some microphone input to a blob/file) and the stream-to-alsa example from node-opus (but using output to a file stream instead of alsa).

Well, the browser as well as VLC can play those files (besides there is no progress bar available) so it can be expected that it is rather a problem of node-opus. But I had a look in its source code and it is really a very thin layer to the native libraries. Anyway, I also submitted an issue there.

To make things easier, I attached a problematic sample recorded by this fork of RecorderJS:
[test-file.ogg.txt](https://github.com/chris-rudmin/Recorderjs/files/261125/test-file.ogg.txt)
(The file has to be renamed before because of the file type restrictions on GitHub)

Thanks,
Robbson

**Comment by chris-rudmin** [comment]
@Robbson I tried your sample file and sure enough it crashes vlc for me. however plays back fine in chrome. Analyzing the file with opusinfo and opusdec (ver 0.1.9) shows no problems with the file. My guess is because I am using the newest version of the encoder. Did you use any special options when creating the file?

If you are concerned, you could checkout my sources, change the version of libopus checkout in the make file to the last beta build, and rebuild. It might fix with playback in some older players.

The samplerate 44100 is metadata saying the the original audio was 44100 Hz.

**Comment by chris-rudmin** [comment]
@Robbson, Is there someplace I could look at your node-opus code?

**Comment by chris-rudmin** [comment]
I just looked quickly at the Node-opus readme.  A few things to note:  They are using in their example a 10ms frame size.  Recorderjs uses 20ms. I assume your audio device sample rate is 44100 Hz (based on your sample file). I imagine you will decode the file at 48000 Hz, but you won't be able to playback a stream of that sample rate. You will need to resample the stream to 44100 before you can play it back.

**Comment by Robbson** [comment]
Hi Chris,
thank you for your fast response.
Yes, 44100Hz seems to be the input frequency of the signal for the encoding in the browser. I probably got confused because in node-opus it's not clearly recognizable as that. But in opusinfo it's correctly declared as the original input frequency.

So you mean it's a resampling issue on the server side? Well, I tested some of the sample files that are hosted as examples on the opus web site. So node-ogg doesn't seem to work as expected when the original input frequency is 44100 (like in ehren-paper_lights-96.opus) while 48000Hz input is working.






I have to ge

**Comment by Robbson** [comment]
@chris-rudmin 
The test file is from your sample application with all the default parameters.

According to your code you are using the most current version of libopus (1.1.2) that I now also use for node-ogg (just by replacing the sources and rebuild using node-gyp).

I think, if it's just a resampling issue then my PCM output file would just have a wrong frequency so it plays back too slow or fast. But it is doing nothing.

I just debugged the node-ogg native add-on and in case of a 44100Hz original input file the reference to decoder is empty, probably because it couldn't be initialized. Maybe the author of node-ogg got confused by input vs encoding frequency, too.

**Comment by chris-rudmin** [comment]
@Robbson Did I understand that you were able to solve your problems? Actually the doc is not quite clear on that field either. Perhaps I am using it wrong.  What do you think? https://wiki.xiph.org/OggOpus

**Comment by Robbson** [comment]
@chris-rudmin 
Now I have solved the decoding issue using node-opus after reading the libopus docs. ;-)
When you create a new instance of the opus decoder you can specify a decoding frequency that is by default 48000Hz. It is completely independent from the original input frequency and also the one used for encoding. So if you have a target system that requires all output to be at 16000Hz you can set it there and opus does all the resampling for you.

Now, the problem of node-opus is that when you don't specify the decoding frequency it doesn't fall back to 48000Hz. But it uses the original input frequency instead which only works as along as your input frequency is one of those supported by opus. So a 44.1Khz file from e.g. a CD leads to a crash because it can't be set as an decoding frequency.

So all in all you could close this ticket. But there are still two issues with those files coming from your RecordingJS implementation:

1. The last ogg page seems not to be tagged correctly (when using a single POST to the blob) so e.g. VLC plays the last page like a loop.
2. opusdec is able to play those files but it still prints 3 errors to the console before: "Error playing audio". So maybe something is wrong in the header.

Anyway, thanks a lot for your help that pushed me to the right direction.

Robbson

**Comment by chris-rudmin** [comment]
@Robbson I don't get the opusdec error.  Are you decoding to a file or to a stream? Could you copy the error you get into this issue?  

Also I don't quite understand the issue with the last page.  Could you detail how you are using the recorderjs lib and what the exact error is with the last page?

**Comment by chris-rudmin** [comment]
@Robbson Its not clear to me what your setup is.  Are you streaming ogg packets to your node backend and then serving a http data stream for VLC to consume?

When I create a ogg file from Recorderjs and save it locally, I don't see any decoding issues, and VLC correctly shows me the progress when playing back the file. There is also no looping at the end of a file for me.

**Comment by Robbson** [comment]
@chris-rudmin 
I get those opusdec errors (as written above, nothing else, no details are printed) using the ogg-opus file I've attached in my first post. I have a Windows build of the opus tools 0.1.9.
No additional parameters on the command line.

My final goal is to create an audio streaming application for voice processing on the server. But the attached ogg-opus file is from your example application and downloaded from a blob, so no code from myself used.

The missing playback progress is in VLC 2.2.1. But when I change your example to get a dataAvailable event for each ogg page (instead of a single call for all data) then the resulting file (putting all pages together) works with progress in VLC.

I think you can ignore this looping at the end problem because I only get this in ffplay where all opus files are affected so it's probably a bug or feature in that ffmpeg build.

**Comment by chris-rudmin** [comment]
Okay,  just tried with windows, and i see the errors "Error playing audio."
Four times. I dug in the decoder source and I believe it is showing is this
error because the encoder has specified a pre-skip value (to allow decoder
to converge) of 80ms.  This would equal four (20ms) packets at the
beginning of the stream. I believe these "Errors" can be ignored as the
packets are not supposed to be played on purpose. You won't see this
"Error" if you are not using Windows, Linux or if you decode to a file.
