### ISSUE TITLE
Unplayable Blobs

### ISSUE THREAD

**Issue by awjohns** [chris-rudmin/Recorderjs#53]
Maybe I'm doing something wrong, but whenever I have streamPages set to true so that it is outputting chunks all of the blobs / typedarray data is unplayable.

Is it something I may be misunderstanding? Any help would be greatly appreciated. Great work :)

**Comment by chris-rudmin** [comment]
Could you post some code of how you are attempting playback, and what
errors you receive if any?

**Comment by chris-rudmin** [comment]
When stream pages is set to true, you are receive an ogg packet with each
payload. Most use cases for this is streaming to a backend which can
receive the stream as it is being encoded.

**Comment by awjohns** [comment]
Thanks for such a prompt reply! :) I am sending the data through a socket.io emit event to a node server where I send each received chunk into an icecast style server which binds to a specific port with the mime type audio/ogg and chucked encoding. This adds in the metadata that players expect and allows a player such as vlc to play back the audio.

I was originally doing this with a regular ogg encoder (without opus) and that was working. Would I have to decode opus before sending it out as a buffer for vlc players maybe?

Also, just to confirm, so any blobs created with the opus encoded packets in streamPages mode wouldn't play in the audio tag in chrome from e.details right as they aren't currently. Sorry if this is all fairly obvious, trying to feel my way through opus.

Kind Regards,

Adam

**Comment by chris-rudmin** [comment]
Is your library which adds metadata expecting ogg vorbis perhaps?
The Audio tag can play a stream from a streaming uri but not from local
pages I believe.

**Comment by chris-rudmin** [comment]
Could you clarify what you mean by regular ogg?

**Comment by awjohns** [comment]
Sure! By regular ogg I meant without opus. I was previously using OggVorbisEncoder.js and passing the channeldata from audiocontext to it and with the output from that I was able to play the generated chunks through the server.

I am manually piping the data packets and setting mimetypes myself and so the server is just receiving what I send and then the players are getting that packet data with the metadata that has been set. I'm currently using the mimetype of audio/ogg.

Regarding the audio tag, so am I right in thinking that it explains why the audioblobs that get added to the local example page when dataAvailable is fired and streamPages is true aren't able to be played but when streamPages is false the audioblob generated on the example page does play. So that's because the data sent when streamPages is true is different to the data that gets sent when it is false?

**Comment by chris-rudmin** [comment]
What metadata are you setting? I would try not modifying the packets and see if the players are able to play the stream. If you are able to capture the first 3 pages before and after you make the metadata changes, it might help illuminate what the problems are.  The pages you get when `streamPages` is set to true are exactly the same as when it is set to false.

**Comment by awjohns** [comment]
Ahh so it is the same data with both true and false. I'm not actually altering the packets themselves, The players make an icecast connection request separately before they begin to play the data so I return the mime type first and then the raw data that is sent from recorderjs.

Again I apologise if I misunderstand but if the data being output is exactly the same whether streampages is set to true or false shouldn't I be able to play the generated blobs locally before even sending any data?

For example, even in an unedited version of the demo app where I haven't added my socket code to do anything with the data, when streampages is false and you press stop it manually fires ondataavailable and you get a playable blob as expected:

<img width="392" alt="streampages false" src="https://cloud.githubusercontent.com/assets/19618274/15631966/ab3a2824-257a-11e6-96f8-de292ef26776.PNG">

But with streampages set to true each blob that is outputted with the exact same audio packets, the blobs are unplayable. The only thing that has changed in the second picture is setting streampages to true:

<img width="326" alt="streampages true" src="https://cloud.githubusercontent.com/assets/19618274/15631967/b4dde7bc-257a-11e6-94a0-94e7007df15a.PNG">

Is that where I'm finding a problem? Or is that an expected result for a reason I'm not understanding maybe?

Thanks again for your help on this, it is very much appreciated! :)

**Comment by chris-rudmin** [comment]
Right, when `streamPages` is set to `true` we are not actually streaming pages anywhere, the feature has been created so that the implementor can send the pages as he receives them to his backend. You cannot stream pages locally because there is no stream, just a bunch of data blobs. The playback would work for example if you concatenated all your pages together, created a new blob and sent that to your Audio tag.

To create a stream you need to send the pages to your server and serve them over a streaming uri.

**Comment by chris-rudmin** [comment]
Just to clarify, I have never implemented anything like this, but I would imagine you would need to re-encapsulate the ogg stream before serving it over a stream. Are you doing this?

**Comment by awjohns** [comment]
Yes, brilliant thanks very much for your help, you helped me move in the correct direction and I now have a working solution.

Thank you!!! :) And well done again on a great script!

**Comment by murrayju** [comment]
@chris-rudmin I'm having a very similar problem, and the solution here was not clear.

> Just to clarify, I have never implemented anything like this, but I would imagine you would need to re-encapsulate the ogg pages before serving it over a stream.

What does this mean exactly?

In my implementation, I'm taking the bytes from the `ondataavailable` event, and streaming them to the server via `socket.io-stream`. On the server side, I'm taking the stream and (for now) just writing it out to an `output.opus` file. When `streamPages` is `false`, it works great (I can play the .opus file in VLC). When `streamPages` is `true`, VLC complains "Could not demultiplex stream".

If I peek into the binary (as utf8), there is a noticeable difference at the start of the file. While both start with `Ogg`, the non-streamPages file has clear Opus info in the headers, while the streamPages file does not:

Playable file, `streamPages = false` (xxd output)
```
00000000: 4f67 6753 0002 0000 0000 0000 0000 417b  OggS..........A{
00000010: 160e 0000 0000 9610 a236 0113 4f70 7573  .........6..Opus
00000020: 4865 6164 0101 000f 44ac 0000 0000 004f  Head....D......O
00000030: 6767 5300 0000 0000 0000 0000 0041 7b16  ggS..........A{.
00000040: 0e01 0000 007f 2a82 c801 1a4f 7075 7354  ......*....OpusT
00000050: 6167 730a 0000 0052 6563 6f72 6465 724a  ags....RecorderJ
00000060: 5300 0000 004f 6767 5300 00c0 b502 0000  S....OggS.......
00000070: 0000 0041 7b16 0e02 0000 00df b22c 14b9  ...A{........,..
00000080: 03e3 6868 676a 7fca b564 6665 6a6b 8080  ..hhgj...dfejk..
00000090: 8080 8080 8080 8080 8080 8080 8080 8080  ................
```

And the corresponding `opusinfo`
```
Processing file "output.opus"...

New logical stream (#1, serial: 0e167b41): type opus
Encoded with RecorderJS
Opus stream 1:
        Pre-skip: 3840
        Playback gain: 0 dB
        Channels: 1
        Original sample rate: 44100Hz
        Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
        Page duration:   3700.0ms (max), 2500.0ms (avg), 1300.0ms (min)
        Total data length: 32446 bytes (overhead: 1.25%)
        Playback length: 0m:04.919s
        Average bitrate: 52.76 kb/s, w/o overhead: 52.1 kb/s
Logical stream 1 ended
```

Unplayable file, `streamPages = true` (xxd output)
```
00000000: 4f67 6753 0000 c0b5 0200 0000 0000 08ce  OggS............
00000010: 7fbd 0200 0000 ced6 9507 b9db a161 6064  .............a`d
00000020: 657d 8080 8080 8080 8080 e196 8a80 8180  e}..............
00000030: 817e 7a77 7473 7066 6574 8080 8080 8080  .~zwtspfet......
00000040: 8080 8080 8080 8080 8080 8080 8080 8080  ................
00000050: 8080 8080 8080 8080 8080 8080 8080 8080  ................
00000060: 8080 8080 8080 8080 8080 8080 8080 8080  ................
00000070: 8080 8080 8080 80bd ac98 8081 8081 8081  ................
00000080: 8081 8081 8081 8081 8081 807e 817a 7570  ...........~.zup
00000090: 6d6b 6a6b 7b80 8080 8080 8080 8080 8080  mkjk{...........
```

And the corresponding `opusinfo`
```
Processing file "output.opus"...

WARNING: Invalid header page, no packet found
WARNING: Invalid header page in stream 1, contains multiple packets
New logical stream (#1, serial: 5ed39cd6): type invalid
WARNING: stream start flag not set on stream 1
Logical stream 1 ended
```

I know nothing about the actual Ogg/Opus encoding or binary layout, so I have no idea if this is normal.

**Comment by chris-rudmin** [comment]
@murrayju You should read up a bit on the ogg stream format.  When you configure `streamPages: true` each individual ogg page is emitted in the `ondataavailable` event. Each page on its own does not make a valid opus file (ie. they won't be playable in VLC).  I'm not sure what your end goal is, so I don't know how better to help.  Let me know if you have any more questions.

**Comment by TxAg12** [comment]
@murrayju Are you sure you are handling the encoding properly? At any rate, opusinfo gave you a place to start.

For what it is worth, I use streamPages for a web application and it works well. They are streaming by on my server log as I type, I wish I could should you.

The basics of an ogg file are that there are two opus headers, every page must have the same serial number, and there is a sequence number that increments with each page. 

If you show the effort of studying ogg, this might be a good question for StackOverflow.

**Comment by murrayju** [comment]
Currently I'm taking the data from the `ondataavailable` event and writing it to a (nodejs style) stream. This is sent over websockets, and on the server side is passed into [`op_open_callbacks()`](https://mf4.xiph.org/jenkins/view/opus/job/opusfile-unix/ws/doc/html/group__stream__open__close.html#gad183ecf5fbec5add3a5ccf1e3b1d2593), which gives me the error [`OP_ENOTFORMAT`](https://mf4.xiph.org/jenkins/view/opus/job/opusfile-unix/ws/doc/html/group__error__codes.html#gafca3ae244d24e10b2851c77379453220):
> A purported Ogg Opus stream did not begin with an Ogg page, a purported header packet did not start with one of the required strings, "OpusHead" or "OpusTags", or a link in a chained file was encountered that did not contain any logical Opus streams.

@chris-rudmin It seems to me that I'm missing the headers that go at the start of the stream? When `streamPages: false` I can see these headers near the start of the byteArray, but when `streamPages: true` they aren't emitted. Is the expectation that I should write the headers myself?

**Comment by chris-rudmin** [comment]
@murrayju The headers should be in the first two pages emitted.

**Comment by TxAg12** [comment]
But what is the data coming from `ondataavailable`? What happens with the information after `ondataavailable` is on your side, not Opus Recorder. What version are you using? Mine produces the two header pages on initiation (or immediately after stop) rather than on recording start (loading the resources was laggy). My build might be out of date, though. I grab the serial number and otherwise build my own header pages to save data and request overhead. 

I guess my point is that to build a cutting edge streaming app, it's going to take a lot of understanding of what is going on. If you look at your first two pages with streamPages: true, you should notice that the only things that differ between files are the serial numbers and check sums.

**Comment by murrayju** [comment]
It turns out that I was missing the first two events because I was registering the event handler after calling start recording (d'oh). I was also hitting a timeout on the server side, which I removed. All working now, thanks!
