### ISSUE TITLE
ReferenceError: _malloc is not defined

### ISSUE THREAD

**Issue by jibon57** [chris-rudmin/Recorderjs#54]
When I click on the record button it's showing following error:
`ReferenceError: _malloc is not defined`
I didn't change anything. Just testing with the example files. Any suggestion please?

**Comment by chris-rudmin** [comment]
Is working for me in chrome. What browser are you using?  Try the example at this link: https://rawgit.com/chris-rudmin/Recorderjs/master/example/encoder.html

**Comment by jibon57** [comment]
@chris-rudmin, I was working with Firefox 47.0 but the above link is working... Will I need to compile any other js script?

**Comment by jibon57** [comment]
OK, It's working now. Looks like all the 4 js files are required. Thanks

**Comment by chris-rudmin** [comment]
Good to know it is working. If something is not clear in the example or instructions, let me know and I can try and explain it a bit better in the Readme.

**Comment by ohtangza** [comment]
I am experiencing same issue. Is the _malloc() a built-in function in Javascript? I cannot find any declaration of this function in this repository. I tested it with Chrome and Firefox.

**Comment by ohtangza** [comment]
I figured out what was the problem. This library needed to be compiled first to use it. I will update the documentation for more clarity. Thanks for great library.
