### ISSUE TITLE
Which files need to be hosted

### ISSUE THREAD

**Issue by kennynaoh** [chris-rudmin/Recorderjs#56]
Hello @chris-rudmin ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I think the main file is `recorder.js`.
Is necessary to add other dependent js files?
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8685

**Comment by chris-rudmin** [comment]
Recorder.js requires the encoder worker. Decoder worker and wave worker are optional. Leave the issue open and I can update the doc.

**Comment by kennynaoh** [comment]
So, I think it is fine to add only `recorder.js` and `encoder.js`, right?

By the way, I found that there are no `encoder.js` but `oggopusEncoder.js` in old release versions, but I think they are just different naming space, right? I could add these two files.

And there are no encoder file in `v0.1.1`~`v0.3`, are there any other file necessary to add or we can just add `recoder.js` in these versions.

Please help me confirm that.
Thanks for your help!

**Comment by chris-rudmin** [comment]
@kennynaoh To be specific you will need `/build/recorder.min.js` and `/build/encoderWorker.min.js`. Optional libraries for decoding and buildingWavFiles are in `/build/decoderWorkjer.min.js

**Comment by chris-rudmin** [comment]
For older versions I had moved around and renamed files. If my memory serves me correctly, you will need at `recorder.js` `libopus.js` `oggopus.js` and `recorderWorker.js`
