### ISSUE TITLE
Publish npm package

### ISSUE THREAD

**Issue by ajbeaven** [chris-rudmin/Recorderjs#59]
It looks like this is the only fork of Recorderjs that is in active development. Thanks so much for taking up the mantle!

What's the chance of publishing a new npm package?

**Comment by chris-rudmin** [comment]
Do you mean something other than this https://www.npmjs.com/package/opus-recorder?

**Comment by ajbeaven** [comment]
Urgh, whoops. Is this in the docs somewhere?

**Comment by chris-rudmin** [comment]
It's name is specified in the `package.json` file

**Comment by ajbeaven** [comment]
Ahh, neat. Sorry didn't realise that was how it worked (new to NPM). Would recommend adding to the readme all the same :)
