### ISSUE TITLE
Sample Rate must be 48000

### ISSUE THREAD

**Issue by mudcube** [chris-rudmin/Recorderjs#6]
I'm noticing that when setting the sample rate to 44100 (for example) the audio does not record. It seems that setting to 48000, 24000 and 12000 all work. Any thoughts on what might be going on?

Otherwise, everything is working perfectly. Thanks for putting this out there. Really phenomenal contribution to RecorderJS. I recorded over 2-hours with this and saving took only a few seconds to process and was around 15MB :+1:

**Comment by chris-rudmin** [comment]
If you read the doc, 44100 is not a supported sample rate for encoding opus audio. If you record wav, it should be no problem.

**Comment by chris-rudmin** [comment]
I clarified the wording in the readme. Glad to hear that you could get 2 hours with this, I have not tried a recording that long.

**Comment by mudcube** [comment]
Ahh, sorry to miss the obvious, thanks for pointing that out! :)
