### ISSUE TITLE
Seems that the resampler is not working

### ISSUE THREAD

**Issue by rotem925** [chris-rudmin/Recorderjs#60]
Hi,
I'm streaming from recorderjs to node-opus.
On the server when I read the header file it seems like it is still 44100.I also tried to run opusinfo, and still it is 44100. 
Do I miss anything?

this is how I use it on the client:
```js
var rec = new Recorderjs.Recorder({
            encoderPath:'libs/recorderjs/encoderWorker.min.js',
            streamPages:true,
            encoderSampleRate:48000
        });
```
On the server, using node-opus I do:
```js
var oggDecoder = new ogg.Decoder();
            var opusDecoder=null;
            var wavWriter = null;
            var fsOpus = fs.createWriteStream(opusFile);
            oggDecoder.on('stream',function (oggStream) {
                opusDecoder = new opus.Decoder();
                opusDecoder.on('format', function (format) {
                    console.log(format);
                    wavWriter = new wav.FileWriter(pcmFile, {
                        channels: format.channels,
                        sampleRate: format.sampleRate,
                        bitDepth: format.bitDepth
                    });
                    opusDecoder.pipe(wavWriter);
                });
                oggStream.pipe(opusDecoder);

            })
            stream.pipe(oggDecoder);
            stream.pipe(fsOpus);
```

**Comment by chris-rudmin** [comment]
Opus doesn't support 44100 internally. I'm guessing that the rate 44100 you
see is the decoded data sample rate for playback. If you attach a sample
file I can take a look at it.

**Comment by rotem925** [comment]
Sure,
Thank you!
See attached.
[in.opus.txt](https://github.com/chris-rudmin/Recorderjs/files/574088/in.opus.txt)

**Comment by chris-rudmin** [comment]
This is the opusinfo of the file.  What part about this doesn't look right to you? ```New logical stream (#1, serial: f07d0bd4): type opus
Encoded with Recorder
WARNING: EOS not set on stream 1 (normal for live streams)
Opus stream 1:
	Pre-skip: 3840
	Playback gain: 0 dB
	Channels: 1
	Original sample rate: 44100Hz
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:   3700.0ms (max), 3700.0ms (avg), 3700.0ms (min)
	Total data length: 23777 bytes (overhead: 1.31%)
	Playback length: 0m:03.620s
	Average bitrate: 52.55 kb/s, w/o overhead: 51.86 kb/s```

**Comment by chris-rudmin** [comment]
`Original sample rate: 44100Hz` means that the original audio had a bandwidth of 44100Hz. Judging from your code snippets, it was then up-sampled to 48000Hz for encoding with opus.  This all looks as expected.

**Comment by rotem925** [comment]
I'm getting an error from node-opus (Maybe it related to node-opus)
Error: Could not create decoder. Check the decoder parameters
When looking into node-opus code, it seems like it sends the header sampleRate to the opus decoder, and opus decoder does not support it.
Any idea what's going on? If for example I modify the code and hard code 48000, it works.

**Comment by chris-rudmin** [comment]
Yeah, seems that node-opus is using the header defined sample rate to try and decode.  I opened an issue here: https://github.com/Rantanen/node-opus/issues/20

**Comment by rotem925** [comment]
Ok. Thanks,
Still, if I try to play the file after the decoding.. it different (like slower..)

**Comment by chris-rudmin** [comment]
Likely because you are decoding at 48000 Hz and then playing it back at 44100Hz without resampling?

**Comment by rotem925** [comment]
Ok, so I need to downsample it then... Thank you for the help. Do you know if there is a library that downsample?

**Comment by chris-rudmin** [comment]
Lots of them. Easiest would probably be to pipe your output to SOX

**Comment by rotem925** [comment]
Ok,
Thank you!
I think we should close this issue as it is not related to recorderjs.

**Comment by rotem925** [comment]
See my pull request on node-opus:
https://github.com/Rantanen/node-opus/pull/21

Hope that should solve it.

**Comment by chris-rudmin** [comment]
Cool. :+1:
