### ISSUE TITLE
Should I stop a recorder instance if a user leaves a page just after recorder initialization?

### ISSUE THREAD

**Issue by seabrus** [chris-rudmin/Recorderjs#63]
QUESTION

If a user makes a recorder initialization (`init.addEventListener("click", function () {...}` - this event is happened) but does NOT start recording and then leaves a webpage with audio recording functionality, should I call `recorder.stop()` when the page is left to stop the audio recording processes or they are stopped automatically in some way? 

TESTIMONIAL

Thank you very much from my children for your package that has helped to develop my app. Using it I record and share with them fairy tales, they like them very much.

Have a nice day!

**Comment by chris-rudmin** [comment]
I suppose the behaviour depends on your website. If you have a single page app, then a page (state) change might leave the audio recording. If the new page does a complete refresh, the recording should stop and javascript objects cleaned up.

**Comment by seabrus** [comment]
understood, thx!
