### ISSUE TITLE
example encoder from wav file, not microphone

### ISSUE THREAD

**Issue by erez-o** [chris-rudmin/Recorderjs#66]
Hi, 
 
I need to compare the encoding to that of lib-opus-tools that runs on files. 

Do you have a working encoder.html example where the input is a wav/pcm file instead of the microphone?

I tried creating a working example, but was unsuccessful.

Thx

**Comment by chris-rudmin** [comment]
I don't have a working example of that, but should be feasible.  Read out the wave file PCM data into chunks equivalent of the buffer size and send into the encoderWorker

**Comment by chris-rudmin** [comment]
For working with files, the tools [here](http://opus-codec.org/downloads/) should be much more suited for the job.

**Comment by erez-o** [comment]
Hi, 

Attached is a fileEncoder example. I had to change the extension from html to txt.

There is no "LastBuffer" message in the encoder, so the fileEncoder.html implementation appends multiple audio tags, and the last one is the full audio. 

It's not a good implementation, so I think the encoder should send a message `self['postMessage'](null);` as you did for the decoder in https://github.com/chris-rudmin/Recorderjs/blob/master/src/decoderWorker.js#L140 , but I haven't tested it yet. I'll test it and send a pull request.

Note - The reason I think having an option to work with files is important is to check the quality of the encoder in a consistent way, and to compare it to the tools. There are flags like encoder complexity and others that I'll add to the options and send a pull request (see https://github.com/chris-rudmin/Recorderjs/blob/master/src/encoderWorker.js#L184), define 4010 in addition to 4002. 

[fileEncoder.txt](https://github.com/chris-rudmin/Recorderjs/files/802835/fileEncoder.txt)

Thx
