### ISSUE TITLE
iPhone iOS 10.2.1 - "Recording features are not supported in your browser"

### ISSUE THREAD

**Issue by seabrus** [chris-rudmin/Recorderjs#68]
Hi,

**Environment**: iPhone 6 with iOS 10.2.1 
**Browsers**: Safari, mobile Chrome

`Recorder.isRecordingSupported()` returns `false` and I got an error `Recording features are not supported in your browser`: 

![3](https://cloud.githubusercontent.com/assets/10603559/23036520/cdf26ff8-f48b-11e6-8594-bd4bf9eb1af8.jpg)

On the Apple laptop and PCs this functionality works fine.  
Trying to understand what may be the reason, but still without any result. Will be very grateful for any help or hint.

**Comment by chris-rudmin** [comment]
My best guess Is that safari on iOS does not have an implementation of AudioContext. MDN seems to suggest as much.

**Comment by chris-rudmin** [comment]
Looks like `navigator.getUserMedia()` has been deprecated in favour of `navigator.mediaDevices.getUserMedia()`. Should be fixable.

**Comment by seabrus** [comment]
@chris-rudmin 
> safari on iOS does not have an implementation of AudioContext

-- it was my first guess too. But at [DeveloperApple](https://developer.apple.com/reference/webkitjs) => [AudioContext](https://developer.apple.com/reference/webkitjs/audiocontext) is described as supported for both Safari Desktop 10.0+ and Safari Mobile 9.0+ SDKs.

As for [navigator](https://developer.apple.com/reference/webkitjs/navigator) (SDKs:  Safari Desktop 10.0+ and  Safari Mobile 3.0+), the situation looks less promising:
- [mediaDevices](https://developer.apple.com/reference/webkitjs/navigator/1630781-mediadevices) is marked as part of Safari Desktop 10.0+ SDK only, 
- [webkitGetUserMedia](https://developer.apple.com/reference/webkitjs/navigator/1630123-webkitgetusermedia) is used in SDK for Safari Desktop 9.0+ -- again no Safari Mobile mentioned. 

Also the **Browser compatibility** section in the articles about 
- [Web Audio API (AudioContext interface)](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API), 
- [MediaDevices.getUserMedia()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), 
- and [MediaDevices](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices) 

at MDN: `AudioContext` is supported but no support for `MediaDevices` and `MediaDevices.getUserMedia` on Safari :(

**Comment by chris-rudmin** [comment]
Yup, I checked some more, looks like iOS is not supported.
