### ISSUE TITLE
is it possible to broadcast streamPages data for live listening

### ISSUE THREAD

**Issue by kkxlkkxllb** [chris-rudmin/Recorderjs#69]
can it used  to be a web radio station publisher?
i have seen "streamPages" config option, it will output Uint8Array data, i can broadcast these data to other client side with socket.io, but i have no idea about how to make these steamPages played on the other client side.

**Comment by chris-rudmin** [comment]
I know some people have used this library in conjunction with WebRTC. Might be what you are looking for?

**Comment by kkxlkkxllb** [comment]
That's fine, where can i see the source code of those projects?

**Comment by chris-rudmin** [comment]
Not sure, you'll have to do some googling.  I notice that lots of ogg opus audio streams are served using icecast.  Might be a good place to start your investigation.

**Comment by chris-rudmin** [comment]
Maybe this? https://github.com/webcast/webcaster

**Comment by kkxlkkxllb** [comment]
Thanks a lot!
