### ISSUE TITLE
Updating Opus and Speex

### ISSUE THREAD

**Issue by erez-o** [chris-rudmin/Recorderjs#71]
Hi, 

Any reason not to update the latest Opus and Speex?

LibOpus new stable is 1.1.4 (currently using 1.1.2)
Speex new stable is 1.2.0 (currently using 1.2rc3)

I think it might be a good idea to add some audio files to the project as tests, and run encode & decode on them.

**Comment by chris-rudmin** [comment]
Cool. I have a branch where I started adding unit tests and experimenting with updated versions. Will definitely do this

**Comment by erez-o** [comment]
Cool

**Comment by chris-rudmin** [comment]
Let's keep this open. I'll close it when i have it merged and tested.

**Comment by chris-rudmin** [comment]
Update Libopus to 1.1.4, SpeexDSP stable is still at 1.2rc3 (note that we are using the repo for `SpeexDSP` and not `Speex`).
