### ISSUE TITLE
Performance in mobile

### ISSUE THREAD

**Issue by erez-o** [chris-rudmin/Recorderjs#72]
Hi, 

Any benchmarks have been done on mobile devices? especially mobile devices that are not top of the line?

If there's a need, I can add support for `_opus_encode_fixed` in addition to `_opus_encode_float`.

**Comment by chris-rudmin** [comment]
iOS is not supported. I don't have any benchmarks, but my low powered MOTO E Android phone seems to encode without much trouble.

**Comment by chris-rudmin** [comment]
I would be curious to see if there are any performance gains to be had.  Javascript operates with floating point, and incoming audio is float 32 so I would be sceptical that converting data to fixed point would have any advantages.

**Comment by erez-o** [comment]
Good points.

I'm also happy to hear that it works well even for MOTO E.

Sorry for the stupid question, but why is IOS not supported? I know that IOS can't play ogg, but is there any problem for the use case where audio from the microphone is encoded and sent to a server?

**Comment by chris-rudmin** [comment]
iOS does not allow browser access to the microphone.  

Also note that the compilation of opus with emscripten has all SSE optimizations disabled. I receive compilation errors when trying to add them.  I was able to compile speex with SSE optimizations and SIMD, but it performs about 10x worse than without.

**Comment by erez-o** [comment]
Thx very much for all the great info :)
