### ISSUE TITLE
WavWorker won't fire onmessage event

### ISSUE THREAD

**Issue by haste-jeff** [chris-rudmin/Recorderjs#73]
I'm currently attempting to use RecorderJS to encode, immediately decode, and play out the information through my speakers. Doing this would mean that I could encode the data and send it across the internet to some endpoint as a stream and decode it there.

Now, I'm assuming that, given the decoder example, it is necessary to run the decoded data through the wavWorker in order to get it into a raw format that can be played through the speakers. The problem is that the wavWorker's onmessage event never fires when I try to send it a decoded message.

Here's the relevant code I have.

```
let aCtx = new AudioContext()

let config = {
	encoderPath: "/assets/encoderWorker.min.js",
	streamPages: true
}
let rec = new Recorder(config)
let decoderWorker = new Worker('./assets/decoderWorker.min.js')
let wavWorker = new Worker('./assets/waveWorker.min.js')

rec.addEventListener( "streamReady", function(e){
    console.log('Audio stream is ready.')
	rec.start()
})
	  
rec.addEventListener( "dataAvailable", function(e){
    decoderWorker.postMessage({
      command: 'decode',
      pages: e.detail
    }, [e.detail.buffer] )
})

decoderWorker.onmessage = function(e){
    if (e.data === null) {
		console.log("It's done")
		wavWorker.postMessage({ command: 'done' })
    }
    else {	
		wavWorker.postMessage({
        command: 'record',
        buffers: e.data
        }, e.data.map(function(typedArray){
            return typedArray.buffer;
          }));
		  
    }
}

wavWorker.onmessage = function(e){
	console.log("Got a wav message") /* Never fires */
}
	  
decoderWorker.postMessage({ 
        command:'init'
    })
	
wavWorker.postMessage({ 
    command:'init'
});
	  
rec.initStream()
```

Any help would be appreciated.

**Comment by chris-rudmin** [comment]
waveWorker might needs some initialization params to work properly. Depends what format your audio is getting decoded as. See [here](https://github.com/chris-rudmin/Recorderjs/blob/master/src/waveWorker.js#L25). If you use the Chrome debugger, you can debug web workers and see whats going on.

**Comment by haste-jeff** [comment]
I actually deleted the initialization parameters that were shown in the example because they lined up with decoderWorker's defaults, such as the default sample rate being 48000 for both. That said, something like bitDepth could be wrong if it doesn't encode it at 16 bits. Not sure on that.

Your suggestion of using the Chrome debugger sounds like the way to go. I'll see if I can find anything out with that and get back to you.

**Comment by chris-rudmin** [comment]
You can use the un-minified waveWorker as well. Will be easier to read.

**Comment by haste-jeff** [comment]
I think I just realized what the problem is.

The onmessage command only fires after you send waveWorker a 'done' message. Essentially, while the encoder and decoder can handle streams, waveWorker is not currently set up to--it expects to get all of its data, then output once.

**Comment by chris-rudmin** [comment]
Correct. A wave file has the length encoded into the header so it cannot be
exported until the whole file is complete.

**Comment by haste-jeff** [comment]
I think I misunderstood the point of the waveWorker then. Am I correct in assuming that waveWorker is just for making whole files, and that audio data that is decoded with decodeWorker does not need any additional processing in order to play them out the speakers?

The thing is, I tried pushing out the data that I received from the decodeWorker right to the speakers using AudioContext, but it didn't work--it just emitted a buzzing noise. So I thought I needed the waveWorker. But now I'm thinking I just did it wrong, and I should be able to play the data I got from the decodeWorker. Is this accurate?

**Comment by chris-rudmin** [comment]
Yes, you can load the decoded audio into an audio buffer and play it back.

**Comment by chris-rudmin** [comment]
I don't quite understand what you are trying to achieve? Encode -> decode -> playback as the chunks are being processed? I don't get the point of this exercise. 

Might be possible with some queuing mechanism using two or more audio buffers. You can load the decoded chunks into an audioBuffer and playback, but there might be glitching as you move from one audioBuffer to the next.

**Comment by haste-jeff** [comment]
The point of this exercise is to eventually do this:

Encode -> Send off to server -> server sends to client -> decode -> playback. Essentially, voice chat without WebRTC, since I don't want to use ICE.

But from what you are telling me is that the waveWorker is completely not necessary for this. I believed it to be necessary since pushing the recorded data to an AudioContext destination (the speakers) was just making a buzzing sound. Do you know if I have to use an audio tag instead, or if I simply can't play an incomplete stream?

**Comment by chris-rudmin** [comment]
If you are serving an ogg file from a server and the browser supports opus,
I believe that you can serve it as a stream and start playback before the
stream is complete. Without the server component I don't believe it will
work easily.

**Comment by chris-rudmin** [comment]
Check the headers and payload to see how ICE does it:
http://ascolta.radiogibson.net:8888/radiogibson.opus

**Comment by chris-rudmin** [comment]
Also, opus decode should probably be done natively by the browser codec.  I'm not sure that js implemented decode will be fast enough for real time chat.

**Comment by haste-jeff** [comment]
Can't do it natively at this time. Chrome doesn't support audio/ogg;codec=opus. Firefox could handle the decoding just fine, but my issue is getting the two browsers to talk to each other.

Good call on checking to see how WebRTC/ICE does it.

**Comment by chris-rudmin** [comment]
Native Opus playback works without problems for me with Chrome on Android and Mac. Currently running v56.

**Comment by haste-jeff** [comment]
Then I may have jumped the gun on what I need to use. Chrome's MediaRecorder does not support audio/ogg;codec=opus, so I must have assumed its playback did not work either.

If Firefox works too then I don't need the decoder/waveWorker stuff after all, and all I need is the encoder when using Chrome, which would be superb.

**Comment by haste-jeff** [comment]
I just double checked. I can play Opus in both browsers. This means I only need to use RecorderJS to encode Ogg when using Chrome.

Thanks for pointing this out to me. You've been a great help.
