### ISSUE TITLE
Load this library in single page application

### ISSUE THREAD

**Issue by mattmusc** [chris-rudmin/Recorderjs#74]
Hello,

I am experiencing an issue while using this library in a client side application.
I have included both the `encoderWorker.min.js` and the `recorder.min.js` in my page.

The `new Worker()` function seems to make a request `GET http://localhost:3000/encoderWorker.min.js`. But this is not my path, that file is in `/js/encoderWorker.min.js` and should be searched there.

What am I doing wrong?

Attached:

- Relevant part of `gulpfile.js`
```js
gulp.task("js-libs", function() { 
  return gulp
    .src([
      config.bowerDir + "/jquery/dist/jquery.min.js",
      config.node_modules + "/opus-recorder/build/*.js"
    ]) 
    .pipe(gulp.dest(config.appPath + "/js")); 
});
```
The files are correctly copied into `/js/` folder.

- Relevant part of index.html
```html
...
<script src="/js/encoderWorker.min.js">
</script><script src="/js/recorder.min.js">
```

Should this library be used only in a Node.js server application?

Thanks

**Comment by chris-rudmin** [comment]
`encoderWorker.min.js` is a webworker and needs to be loaded dynamically. The way to do this is with the config when initializing the recorder. See the `encoderPath` config option in the readme.

**Comment by chris-rudmin** [comment]
Just to clarify, you shouldn't load `encoderWorker.min.js` with a script tag. It gets loaded dynamically with `recorder.min.js`. See `example.html` for reference.

**Comment by mattmusc** [comment]
Thank you. I will try it soon.

**Comment by mattmusc** [comment]
It worked. I did as you mentioned.

Another question: Why are you creating a new recorder object and attaching the listeners to the recorder in a callback to the `.on('click')` ? Can I create the recorder and attaching listeners outside?

**Comment by chris-rudmin** [comment]
I do it on the click event because I need to create the recorder instance before attaching events. You can attach listeners however you like. :)
