### ISSUE TITLE
Issue using streamPages : true

### ISSUE THREAD

**Issue by Raukk** [chris-rudmin/Recorderjs#78]
I'm trying to use the example code which works great, but when I change config to "streamPages : true" and it is only calling "dataAvailable" every second or two, this seems like a bug from the stated intent of "Library will fire dataAvailable event after each encoded page"

Am I doing something wrong?

I wan't to use this project for encoding Audio as it is streamed to the server for a chat application.

**Comment by Raukk** [comment]
I might have figured it out. You might want to provide a bit more explanations of what each config parameter does in the description. 
Also, you might want to provide a few simple example configs, like for real-time audio streaming, standard recording, etc.

**Comment by chris-rudmin** [comment]
@Raukk Glad you figured it out. Feel free to make a pull request to clarify any config params which were inadequately explained.

**Comment by chris-rudmin** [comment]
@Raukk Did you have a look at the examples in the `example` folder?
