### ISSUE TITLE
Not working in Firefox v53

### ISSUE THREAD

**Issue by tourdefran** [chris-rudmin/Recorderjs#79]
Firefox v53
I'm getting this error: 
> TypeError: e.navigator.getUserMedia is not a function

**Comment by chris-rudmin** [comment]
Thanks for the bug. Looks like `getUserMedia` has finally been deprecated. I will put a fix in shortly

**Comment by chris-rudmin** [comment]
New version v0.6.0 has the fix. Try it out.

**Comment by tourdefran** [comment]
Hi Chris, thanks for the support!
I have tried the fix in Firefox 53, and 54a2 (devs edition) without success. I don't get the errors in the console, but the audio is not recorded. The implementation of the new method is correct, I have the same error with the official tests of mozilladevs: 

https://mozdevs.github.io/MediaRecorder-examples/
( Record live audio. / Using live audio in Web Audio context )

No problems with Chrome. Please tell me, did you test it in firefox?
thanks!

**Comment by chris-rudmin** [comment]
Validated with Firefox 53.0.2 64 bit running on MacOS 10.12.4

**Comment by chris-rudmin** [comment]
@tourdefran Oups you are right, looks like it works but no audio is recorded.
I will investigate a bit more

**Comment by chris-rudmin** [comment]
My issue seems to be Firefox does not support certain sample rates. The Recorder works fine when system audio is configured to anything below 96k sample rate.  @tourdefran If you check your system audio sample rate and restart Firefox does it fix your issue?

**Comment by tourdefran** [comment]
A friend did a test on a Macbook pro running FFv53 64bits and worked.
I just installed FFv53 64bit on pc Win7 and no audio was recorded. 

![image](https://cloud.githubusercontent.com/assets/2666701/25758167/cee680c0-31a3-11e7-8718-c57a65cee6db.png)

**Comment by tourdefran** [comment]
@chris-rudmin My current sample rate settings are: 48000hz 16bit and 2 channels. I will try 16k to double check

**Comment by chris-rudmin** [comment]
My test on Windows 10 has the same results, recording works up to 48000 Hz sample rate

**Comment by tourdefran** [comment]
Thanks for your test
Well, It's a Firefox thing, not the plugin implementation, and it's related to this I guess...
https://bugzilla.mozilla.org/show_bug.cgi?id=1249098

Now I'm battling with another issue, looks like navigator.mediaDevices.getUserMedia only works with https (secure origins)

**Comment by chris-rudmin** [comment]
Okay, will close this one.  Thanks!

**Comment by tourdefran** [comment]
@chris-rudmin thank you for your help! great library by the way!
