### ISSUE TITLE
Handle getUserMedia failure

### ISSUE THREAD

**Issue by b1rdex** [chris-rudmin/Recorderjs#8]
For now error is just thrown.

https://github.com/chris-rudmin/Recorderjs/blob/master/recorder.js#L164

**Comment by chris-rudmin** [comment]
Would help me if you could post the error. See error codes here:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

**Comment by b1rdex** [comment]
Why you closed this?

![image](https://cloud.githubusercontent.com/assets/312855/6918279/ce6e4e1c-d7ef-11e4-9218-0959d7673d7a.png)

To get this: click init, click start. On request permission panel click deny. It must be `PERMISSION_DENIED`.

There is another error possible if no mic peresent: `MANDATORY_UNSATISFIED_ERROR` I think.

Despite the reason, this errors must be handled and not just rethrown, because this rethrown errors can't be `catch`ed from `(new Recorder).start()` calls.

**Comment by chris-rudmin** [comment]
You are right. I'll add a feature to publish error events.

**Comment by chris-rudmin** [comment]
Added error handling event.
