### ISSUE TITLE
Can't record at 16000hz

### ISSUE THREAD

**Issue by hrss** [chris-rudmin/Recorderjs#80]
I tried to record the audio at 16000hz, but no matter what I do, it always end up being 48000hz. The other configs seem to work. Here is the code:

recorder = new Recorder({
            monitorGain: parseInt(0, 10),
            numberOfChannels: parseInt(1, 10),
            bitRate: parseInt(16000, 10),
            encoderSampleRate: parseInt(16000, 10),
            encoderPath: "encoderWorker.min.js",
            leaveStreamOpen: true
        });

**Comment by chris-rudmin** [comment]
As specified in the readme: `bitRate (optional) Specifies the target bitrate in bits/sec. The encoder selects an application-specific default when this is not specified.` Sounds like what you want to change is the sampleRate. Is this correct? Reading the opus [wiki](https://en.wikipedia.org/wiki/Opus_(audio_format)) might help clarify the difference between the two.

**Comment by chris-rudmin** [comment]
The opus encoder always works internally at 48000 Hz,  When you decode it, it will be decoded natively to 48000 Hz, but the data will be bandwidth limited to 16000 Hz if you do a Fourier analysis.

**Comment by chris-rudmin** [comment]
It should be easy enough to tell if audio is limited to 16000Hz sample rate by ear as all the upper frequencies (above 8000Hz) will be gone. If you do an A/B comparison with some voice, One should sound more muffled than the other.

**Comment by hrss** [comment]
Yeah, sorry for not saying that. I want to change the sample rate. The problem is that when I record some audio with that config, VLC tells me the sample rate is 48000hz, not 16khz. I'm trying to send the audio to google cloud's speech api, but they are very restrict about the sample rate when the encoding is opus.

**Comment by chris-rudmin** [comment]
Opus operates internally at 48000Hz. You need to specify to the decoder (in your case VLC) that you want 16000Hz sample rate output. By default the libopus decoder will give output data at the default rate of 48000 Hz regardless of the encoded rate.

**Comment by chris-rudmin** [comment]
Does google cloud api reject the file as well?

**Comment by chris-rudmin** [comment]
I made a [test with the encoder flag for maxBandwidth](https://rawgit.com/chris-rudmin/Recorderjs/maxBandwidth/example/encoder.html), but VLC still reports sampleRate at 48000 :(. Did my explanations about the behaviour of opus resolve this issue for you?

**Comment by hrss** [comment]
Hey Chris. The api rejects the file. Unfortunately, there's no way to configure the sample rate output in the api. I'll have to use a pcm recorder for now. But thanks man.

**Comment by chris-rudmin** [comment]
It would be great if it worked. :) Attach any logs, and when I have a moments I'll see if there is some way to get it to work.

**Comment by chris-rudmin** [comment]
Or if you could attach a working opus file, we could inspect the headers and see what is different.

**Comment by chris-rudmin** [comment]
It is possible that google cloud is using the `input sample rate` [field](https://wiki.xiph.org/OggOpus#ID_Header) to determine if the file is encoded at 16000Hz. This field is for the original sample rate and _not_ the encoded sample rate. However if you change your device sample rate to 16000Hz before recording, it will set 16000Hz in that field and it may pass their checks

**Comment by hrss** [comment]
Hmm. Ok, I'll try to see if that works.

**Comment by agentmario** [comment]
Google Speech API rejected my file too.

**Comment by chris-rudmin** [comment]
@hrss @agentmario Can you specify which API endpoint you are using and I can try it out myself.

**Comment by chris-rudmin** [comment]
I could not get a vanilla opus file encoded using opusenc and not recorderjs, to work with google speech API. I opened a ticket with google so perhaps we will get a response on Monday.

**Comment by chris-rudmin** [comment]
@agentmario @hrss I added a fix in the latest release that allows customization of input sample rate field using config option `originalSampleRateOverride: 16000`. Confirmed that the encoding now work with Google Speech API.

**Comment by hrss** [comment]
Wow, that helps a lot Chris. Thanks man! Sorry I didn't help you much with this. I ended up implementing the stuff I was doing usim pcm, but now I'll go back to ogg.

**Comment by skusunam** [comment]
@hrss Is this working for you? I just tried this "originalSampleRateOverride: 16000" but still get same error?

{
  "error": {
    "code": "BadRequest",
    "message": "Invalid Audio Format: Require Sample Rate 16k"
  }
}

**Comment by hrss** [comment]
I'm using it like this:

 recorder = new Recorder({
    monitorGain: parseInt(0, 10),
    numberOfChannels: parseInt(1, 10),
    bitRate: parseInt(16000, 10),
    encoderSampleRate: parseInt(16000, 10),
    originalSampleRateOverride: parseInt(16000, 10),
    encoderPath: "encoderWorker.min.js",
    leaveStreamOpen: true
  });


And it it is working. Hope you can find what the problem is. I think the number of channels should be one (mono).
Thanks for your help again, Chris!
