### ISSUE TITLE
only speex whithout ogg header

### ISSUE THREAD

**Issue by icode** [chris-rudmin/Recorderjs#82]
i use for rtmp on websocket, but not work

**Comment by chris-rudmin** [comment]
I don't understand what the issue is. Could you please explain a bit more?

**Comment by icode** [comment]
not have speex cocdec?

**Comment by icode** [comment]
@chris-rudmin  I need speex codec, i found a js lib `speex.js`, but it not work and not update long time. Can you support speex encoder? please, thanks

**Comment by chris-rudmin** [comment]
This is an opus library. I do not have any intentions of supporting the outdated speex codec.
