### ISSUE TITLE
Prefer MediaStream Recording API

### ISSUE THREAD

**Issue by chris-rudmin** [chris-rudmin/Recorderjs#86]
We should prefer MediaStream Recording API, and fallback to compiled code if not present.

**Comment by jareks** [comment]
From my quick and dirty experiments it looks like MediaStream Recording API is not  that reliable at the moment:
- only firefox supports ogg/opus file format, while chrome only allows webm container
- you dont have a fine grain control over encoder - no number of channels, voice type settings are available AFAIK
- you can't implement streaming in similar manner as you did already

**Comment by chris-rudmin** [comment]
@jareks Thanks for the investigation. Good to know

**Comment by TxAg12** [comment]
I am using this specifically because the native MediaRecorder is too basic and, in Chrome, supports only WebM. I second that there are not enough configuration opportunities in the native implementation.

Though it is pretty easy to do streaming with the native MediaRecorder.
