### ISSUE TITLE
How do you get the actual recorder ogg?

### ISSUE THREAD

**Issue by dgaido** [chris-rudmin/Recorderjs#87]
`this.rec.addEventListener('dataAvailable', (event) => {
          let blob = new Blob(event.detail, {type: 'audio/ogg'});
          let fileReader = new FileReader();
          
           fileReader.onload = function (evt) {
                console.log(evt.target.result);
            };
            // Load blob as Data URL
            fileReader.readAsDataURL(blob);
        });`

This snippet works perfectly, but! The resulting base64 encoded file is not valid. What am I doing wrong?

**Comment by dgaido** [comment]
Found how it work by looking at the workers.

**Comment by Gregoor** [comment]
@dgaido care to elaborate?
