### ISSUE TITLE
varying encoder bitrates

### ISSUE THREAD

**Issue by lepinsk** [chris-rudmin/Recorderjs#9]
Hey Chris,

I'm loving the work you've done here.

I've played around with changing the target bitrate of the encoder, which seems to be working reasonably well. Right now my modifications to ```initCodec``` look something like this: 

```js
OggOpus.prototype.initCodec = function() {
  this.encoder = _opus_encoder_create( this.outputSampleRate, this.numberOfChannels, this.encoderApplication, allocate(4, 'i32', ALLOC_STACK) );

  // here we go
  var targetBitrate = 192000;
  var bitrateLocation = _malloc(4);
  HEAP32[bitrateLocation >>> 2] = targetBitrate;
  _opus_encoder_ctl(
    this.encoder,
    4002, // this translates to 'OPUS_SET_BITRATE_REQUEST'
    bitrateLocation)
  ;
  _free(bitrateLocation);
  // all done

  this.encoderBufferIndex = 0;
  this.encoderSamplesPerChannelPerPacket = this.outputSampleRate * this.encoderFrameSize / 1000;
  this.encoderBufferLength = this.encoderSamplesPerChannelPerPacket * this.numberOfChannels;
  this.encoderBufferPointer = _malloc( this.encoderBufferLength * 4 );
  this.encoderBuffer = HEAPF32.subarray( this.encoderBufferPointer >> 2, (this.encoderBufferPointer >> 2) + this.encoderBufferLength );
  this.encoderOutputMaxLength = 4000; 
  this.encoderOutputPointer = _malloc( this.encoderOutputMaxLength );
  this.encoderOutputBuffer = HEAPU8.subarray( this.encoderOutputPointer, this.encoderOutputPointer + this.encoderOutputMaxLength );
};
```

At higher bitrates, however, this seems to be producing files that ```opusinfo``` identifies some problems with. For example, after setting ```targetBitrate = 192000``` above:

```
lappy486:Desktop theoffice$ opusinfo 192k.ogg 
Processing file "192k.ogg"...

New logical stream (#1, serial: 00000539): type opus
Encoded with Recorder
WARNING: Sample count ahead of granule (364800>363840) in stream 1
WARNING: Sample count ahead of granule (606720>605760) in stream 1
WARNING: Sample count ahead of granule (842880>841920) in stream 1
WARNING: Sample count ahead of granule (1562880>1561920) in stream 1
WARNING: Sample count ahead of granule (1801920>1800960) in stream 1
WARNING: Sample count ahead of granule (1922880>1921920) in stream 1
WARNING: Sample count ahead of granule (2164800>2163840) in stream 1
WARNING: Sample count ahead of granule (2409600>2408640) in stream 1
WARNING: Sample count ahead of granule (2526720>2525760) in stream 1
WARNING: Sample count ahead of granule (3010560>3009600) in stream 1
WARNING: Sample count ahead of granule (3130560>3129600) in stream 1
WARNING: Sample count ahead of granule (3248640>3247680) in stream 1
WARNING: Sample count ahead of granule (3493440>3492480) in stream 1
WARNING: Sample count ahead of granule (3615360>3614400) in stream 1
WARNING: Sample count ahead of granule (3737280>3736320) in stream 1
WARNING: Sample count ahead of granule (3859200>3858240) in stream 1
WARNING: Sample count ahead of granule (3978240>3977280) in stream 1
WARNING: Sample count ahead of granule (4100160>4099200) in stream 1
WARNING: Sample count ahead of granule (4344960>4344000) in stream 1
WARNING: Sample count ahead of granule (4589760>4588800) in stream 1
WARNING: Sample count ahead of granule (4710720>4709760) in stream 1
WARNING: Sample count ahead of granule (4955520>4954560) in stream 1
WARNING: Sample count ahead of granule (5200320>5199360) in stream 1
WARNING: Sample count ahead of granule (5445120>5444160) in stream 1
WARNING: Sample count ahead of granule (5689920>5688960) in stream 1
WARNING: Sample count ahead of granule (5934720>5933760) in stream 1
WARNING: Sample count ahead of granule (6179520>6178560) in stream 1
WARNING: Sample count ahead of granule (6300480>6299520) in stream 1
WARNING: Sample count ahead of granule (6545280>6544320) in stream 1
WARNING: Sample count ahead of granule (6790080>6789120) in stream 1
WARNING: Sample count ahead of granule (7154880>7153920) in stream 1
WARNING: Sample count ahead of granule (7624320>7623360) in stream 1
WARNING: Sample count ahead of granule (7977600>7976640) in stream 1
WARNING: Sample count ahead of granule (8326080>8325120) in stream 1
WARNING: Sample count ahead of granule (8566080>8565120) in stream 1
WARNING: Sample count ahead of granule (8686080>8685120) in stream 1
WARNING: Sample count ahead of granule (8930880>8929920) in stream 1
WARNING: Sample count ahead of granule (9783360>9782400) in stream 1
WARNING: Sample count ahead of granule (10272000>10271040) in stream 1
WARNING: Sample count ahead of granule (10756800>10755840) in stream 1
WARNING: Sample count ahead of granule (10878720>10877760) in stream 1
WARNING: Sample count ahead of granule (10998720>10997760) in stream 1
WARNING: Sample count ahead of granule (11243520>11242560) in stream 1
WARNING: Sample count ahead of granule (11364480>11363520) in stream 1
WARNING: Sample count ahead of granule (11485440>11484480) in stream 1
WARNING: Sample count ahead of granule (11607360>11606400) in stream 1
WARNING: Sample count ahead of granule (11727360>11726400) in stream 1
WARNING: Sample count ahead of granule (11846400>11845440) in stream 1
WARNING: Sample count ahead of granule (12320640>12319680) in stream 1
Opus stream 1:
	Pre-skip: 3840
	Playback gain: 0 dB
	Channels: 1
	Original sample rate: 44100Hz
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:   2560.0ms (max), 2492.4ms (avg),   40.0ms (min)
	Total data length: 6203394 bytes (overhead: 0.466%)
	Playback length: 4m:16.639s
	Average bitrate: 193.4 kb/s, w/o overhead: 192.5 kb/s
Logical stream 1 ended
```

I've poked around a bit further, and noticed [this snippet](https://github.com/chris-rudmin/Recorderjs/blob/b4a16320dafd765a9c712a4d1cc885fcd2fb5756/oggopus.js#L107-L111) in ```OggOpus.prototype.generatePage```:

```js
  // Number of samples upto and including this page at 48000Hz, into 64 bits
  pageBufferView.setUint32( 6, granulePosition, true );
  if ( granulePosition > 4294967296 || granulePosition < 0 ) {
    pageBufferView.setUint32( 10, Math.floor( granulePosition/4294967296 ), true );
  }
```

Is it possible that these are related? I'm a bit out of my depth here and trying to figure out whether there are other changes that need to be made to support varying the encoder bitrate. I'd love to hear any thoughts you have on this.

**Comment by chris-rudmin** [comment]
The granule position is used by the decoder to enable seeking. It is assuming a decoded sample rate of 48000Hz. If you encode without your bitrate modifications do you still encounter this error? 
Is your end goal to force a fixed constant bitrate of 192 kb/s?

**Comment by lepinsk** [comment]
No – I only see the errors when I set the bitrate above some value. Setting it to 96000 or 100000 doesn't seem to cause those errors, but 128000 or 196000 does.

192k is definitely not my goal – my first order of business was to figure out how to modify the target bitrate, and I wanted to compare some sample recordings at various bitrates and see if I could find a sweet spot – to see whether 96k gives me any worthwhile gains over the default, for example.

(*Interesting aside:* While the [opusenc docs](https://mf4.xiph.org/jenkins/view/opus/job/opus-tools/ws/man/opusenc.html) state that the encoder defaults to a bitrate of 64kbps per mono stream, when I poll the encoder for its bitrate after initializing, it always returns 72000.)

**Comment by lepinsk** [comment]
If it's of any help, I threw together a very quick demo of this in the ```target-bitrate``` branch here: https://github.com/lepinsk/Recorderjs/tree/target-bitrate

The demo adds an additional field to the webpage where you can set an arbitrary target bitrate value.

**Comment by chris-rudmin** [comment]
It seems the warning is thrown because there are more samples than granule position reports. It's possible there was an error encountered and the granule position wasn't updated for a packet. I don't have any error handling in my code, so if something went wrong i don't know what to expect.  Do you see any errors in the console?

The difference is 960 samples which is exactly the length of one opus packet. Is it always this amount?
Does it always happen even with extremely short recordings? To really get to the bottom of this, you might have to open the debugger and step through the oggopus code while it is encoding to find out where we lose track of one packet.

**Comment by chris-rudmin** [comment]
Just realized that by increasing the bitrate we might be truncating data.  Try increasing the size of the output buffer here: https://github.com/chris-rudmin/Recorderjs/blob/master/oggopus.js#L147

Might fix those warnings.

**Comment by lepinsk** [comment]
Nope, nothing's getting thrown in the console.

It's been 960 samples every time I've checked it. I tried a bunch of recordings of variable lengths:

* 2 seconds: no warnings
* 5 seconds: one warning
* 7 seconds: one warning
* 21 seconds: six warnings

In the 21s recording, ```opusinfo`` also threw the following warning: ```WARNING: Samples with negative granpos in stream 1```, which I don't think I've seen before. From the [opus tools source](https://github.com/gcp/opus-tools/blob/master/src/info_opus.c#L223-L224) there's this comment next to the error:

```
/*There shouldn't be any negative samples after counting the samples in the page backwards
from the first GP, but if this is the last page of the stream there may need to be to trim.*/
```

Perhaps these are unrelated...

**Comment by lepinsk** [comment]
> Try increasing the size of the output buffer here

Hmm, doubled it from 4000 to 8000 (and then 20000) but I'm still seeing warnings on a 24s recording done with a 128kbps target.

**Comment by chris-rudmin** [comment]
well, if you decide to keep debugging, there could be some logic which I am not handling well in segmentPacket(). Check for funny packet sizes (negative values , or very large packets)

**Comment by chris-rudmin** [comment]
I think I found the issue. Pull my commit f0e598 and tell me if it fixes those warnings.

**Comment by lepinsk** [comment]
Hey Chris – looks like that did it. I pulled it into my testing branch and have made a number of test recordings that don't exhibit the problem. Thanks for all your help with this – I owe you a drink next time I'm in Montreal. :+1: 

If you're interested in the configurable bitrate stuff that I did – let me know and I'll package it up as a PR for you.

**Comment by chris-rudmin** [comment]
If you can make the bitrate optionally configurable (as part of the opus configuration object), please send me a PR and i`ll merge it.
