### ISSUE TITLE
More build instructions needed

### ISSUE THREAD

**Issue by muhamed-smajevic** [chris-rudmin/Recorderjs#91]
Can you provide more instructions how to build it, what is needed to compile on Windows 10 etc?

**Comment by chris-rudmin** [comment]
@muhamed-smajevic Unfortunately I don't use Windows, so I can't help you out.  Do you have all the dependencies: Emscripten, automake, autoconf, libtool, pkgconfig? What errors do you receive when building?  If you find out some missing dependencies for Windows, let me know and I'll add it to the readme.

**Comment by chris-rudmin** [comment]
@muhamed-smajevic Looks like you can install the dependencies on Windows using [msys2](http://openframeworks.cc/setup/msys2/) I'll install a windows Virtual Machine and see if it works as I would expect

**Comment by chris-rudmin** [comment]
@muhamed-smajevic Tried to build using msys2 but I ran into a bunch of errors which I could not resolve. If it doesn't work for you, you could try Cygwin. My next suggestion after that would be to install your favorite linux distro into a VM and work that way.

**Comment by muhamed-smajevic** [comment]
@chris-rudmin I haven't managed to compile it yet using windows. I will keep you updated if find solution.
