### ISSUE TITLE
Modern constraint set does not have `mandatory` and `optional` fields

### ISSUE THREAD

**Issue by SaschaNaz** [chris-rudmin/Recorderjs#94]
https://github.com/chris-rudmin/Recorderjs/blob/2d5ea2d8f2d1c7f35e4890e0a191a7a2d829bd0a/src/recorder.js#L28-L36

`streamOptions` field by default uses old format for previous `navigator.getUserMedia` which had `mandatory` and `optional` fields. Modern `navigator.mediaDevices.getUserMedia` removed them and just uses constraint fields directly:

```js
// Example 7 from https://w3c.github.io/mediacapture-main/archives/20170828/getusermedia.html
var gotten = navigator.mediaDevices.getUserMedia({
  video: {
    width: {min: 320, ideal: 1280, max: 1920},
    height: {min: 240, ideal: 720, max: 1080},
    frameRate: 30,     // Shorthand for ideal.
    // facingMode: "environment" would be optional.
    facingMode: {exact: "environment"}
  }});
```

The default `streamOptions` value won't have any effect anyway, but there are some problematic situation as the library is currently directly fallbacking to `navigator.getUserMedia`

1. Browser only supports old `navigator.getUserMedia` but an author writes modern constraint format.
2. Browser supports modern `navigator.mediaDevices.getUserMedia` but an author writes old constraint format with `mandatory` and `optional`.

I think this difference should somehow be taken care of.

**Comment by chris-rudmin** [comment]
@SaschaNaz Good point. I was never able to get consistent behaviour with the streamOptions (note the google specific options) which is why they never made it into the readme. My feeling is to simply remove the options, or just support the current draft of mediaConstraints.  What do you think?

**Comment by SaschaNaz** [comment]
I think it can be polyfilled as the latest draft still have `advanced` field which is described as "optional":

>A User Agent attempts to ensure that sources adhere to advanced (optional) constraints as closely as possible, see 11. Constrainable Pattern.

```js
// Therefore this old format can be:
({
  mandatory: { a:  0  },
  optional: [{ b: 0 }]
});

({
  a: 0,
  advanced: [{ b: 0 }]
});
```

**Comment by chris-rudmin** [comment]
@SaschaNaz I've decided not polyfill the old constraints object. I've left the implementation open for those who wish to use this to validate the spec themselves before supplying a config object. Modern browsers auto update so the number of people using legacy format should be limited.
