### ISSUE TITLE
Promise from `initStream` does not throw when it get an error

### ISSUE THREAD

**Issue by SaschaNaz** [chris-rudmin/Recorderjs#96]
https://github.com/chris-rudmin/Recorderjs/blob/2d5ea2d8f2d1c7f35e4890e0a191a7a2d829bd0a/src/recorder.js#L100-L102

onStreamError does not throw, so the Promise will never throw. It should throw so that its receiver can get notified without adding any event listener.

(Currently receiver can check the return value but it will still not get the error object from Promise)

**Comment by chris-rudmin** [comment]
@SaschaNaz I based the event structure around the MediaRecorder API (https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder).  The MediaRecorder API sends an error event and does not throw an unhandled error. I would like them to remain aligned unless there is a strong argument against.

**Comment by SaschaNaz** [comment]
I think MediaRecorder is not based on Promises. Check out what [`MediaElement.prototype.play()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) does when there is an error: It throws _and_ fires an error event so that both use cases can work.

**Comment by chris-rudmin** [comment]
In the link you shared, it says: `The promise's rejection handler is called with an exception name passed in as its sole input parameter (as opposed to a traditional exception being thrown).` Its still not clear to me what behaviour you think would be ideal.  However feel free to make a pull request and we can review the implementation. :)
