### ISSUE TITLE
volume different between laptop and mobile phone

### ISSUE THREAD

**Issue by zhbnglmm** [chris-rudmin/Recorderjs#98]
I am a middle school teacher and try to develop a website to assign homework to my students. I used the example/waveRecorder.html(never changed any parameters) to develop a recorder for my website. 

If I record thru my laptop and broadcast on my laptop, then the volume is just OK.
If I record thru my mobile phone and broadcast on my mobile phone , then the volume is very good.
If I record thru my mobile phone and broadcast on my laptop, then the volume is very good.
but, If I record thru my laptop and broadcast on my mobile phone, then the volume is very low.
I used firefox on both laptop and mobile phone. I tried to adjust monitorGain but no help. can you give me any advice for it? sorry I am newbie on programming. I didn't know if it is right to post this problem here.

**Comment by djcanard** [comment]
My findings are that the recording volume is very dependent on the microphone settings of the OS, most notably the microphone boost level.
The monitorGain setting is just for the output volume and doesn't affect the input/recording volume.
I think recorderJS should have an input-gain setting to manipulate the recording level.

**Comment by chris-rudmin** [comment]
@zhbnglmm There is an undocumented option to modify the audio constraints.  You could try the auto gain option and see if it helps in your case:

```
var rec = new Recorder({ streamOptions: { autoGainControl: true } });
```

**Comment by chris-rudmin** [comment]
@djcanard If the user has low recording volume from the audio device, It would be more efficient to set the proper gain staging at the input so all software that uses the mic will have the proper volume (gaming, facetime, etc). So instead of adding an additional gain control, I would propose that the user optimize his recording volume by:

1. Moving close to the mic and speak louder
2. Use the system native mic gain control to set an appropriate level globally.

**Comment by djcanard** [comment]
@chris-rudmin you're right, the best option is to set the gain at OS level, but in our setup (for high stakes testing) the end-user is not able to access the OS or it's settings.
We're trying to maximize the gain programmatically in our custom Linux OS though.

**Comment by chris-rudmin** [comment]
@djcanard well if the auto gain doesn’t work as expected you could add a compressor node and a gain node in the audio pipeline to normalize audio

**Comment by zhbnglmm** [comment]
thank you for your advice. I managed to make a better recording volume by using a better mic. Addtionally, I will investigate your proposal. thanks again!
